In [1]:
import os
import gc
import time
import warnings

import torch
import pandas as pd

from tqdm.auto import tqdm

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)

warnings.filterwarnings("ignore")


# ============================================================
# CONFIGURATION
# ============================================================

TRAIN_PATH = r"fewshot_examples.csv"
TEST_PATH  = r"P_CULTA_V2.csv"


# ============================================================
# MODEL
# ============================================================

MODEL_ID = "enstazao/Qalb-1.0-8B-Instruct"


NUM_EPOCHS = 10

MAX_LENGTH = 2048
MAX_NEW_TOKENS = 40


# ============================================================
# QLoRA CONFIGURATION
# ============================================================

LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05


# ============================================================
# TRAINING CONFIGURATION
# ============================================================

BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 8

LEARNING_RATE = 2e-4


# ============================================================
# LOAD DATA
# ============================================================

train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

print("==============================================")
print("DATASET")
print("==============================================")

print(f"Train shape : {train_df.shape}")
print(f"Test shape  : {test_df.shape}")

print("\nColumns:")
print(train_df.columns.tolist())

print("\n==============================================\n")


# ============================================================
# CHECK REQUIRED COLUMNS
# ============================================================

required_columns = [
    "User Utterance",
    "Context",
    "User Role",
    "Model Role",
    "Power Distance",
    "Gold Response",
]

for col in required_columns:

    if col not in train_df.columns:

        raise ValueError(
            f"Missing column in training file: {col}"
        )

    if col != "Gold Response" and col not in test_df.columns:

        raise ValueError(
            f"Missing column in test file: {col}"
        )


# ============================================================
# GPU CHECK
# ============================================================

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU not available."
    )


print("\n================ GPU INFO ================")

print(
    f"GPU : {torch.cuda.get_device_name(0)}"
)

props = torch.cuda.get_device_properties(0)

print(
    f"Total VRAM : "
    f"{props.total_memory / 1024**3:.2f} GB"
)

print(
    f"Allocated : "
    f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB"
)

print(
    f"Reserved  : "
    f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB"
)

print("==========================================\n")


# ============================================================
# SYSTEM INSTRUCTION
# ============================================================

SYSTEM_INSTRUCTION = (
    "Generate a natural Urdu response. "
    "Output only the response utterance. "
    "Do not explain. "
    "Do not narrate. "
    "Do not add extra context. "
    "Do not ask unnecessary follow-up questions."
)


# ============================================================
# 4-BIT QUANTIZATION
# ============================================================

bnb_config = BitsAndBytesConfig(

    load_in_4bit=True,

    bnb_4bit_use_double_quant=True,

    bnb_4bit_quant_type="nf4",

    bnb_4bit_compute_dtype=torch.bfloat16,
)


# ============================================================
# MEMORY PRINT FUNCTION
# ============================================================

def print_memory(title):

    print(
        f"\n================ {title} ================"
    )

    print(
        f"Allocated : "
        f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB"
    )

    print(
        f"Reserved  : "
        f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB"
    )

    print(
        f"Max Allocated : "
        f"{torch.cuda.max_memory_allocated() / 1024**3:.2f} GB"
    )

    print(
        f"Max Reserved  : "
        f"{torch.cuda.max_memory_reserved() / 1024**3:.2f} GB"
    )

    print("==========================================\n")


# ============================================================
# GPU CLEANUP
# ============================================================

def cleanup_gpu():

    gc.collect()

    if torch.cuda.is_available():

        torch.cuda.empty_cache()

        try:

            torch.cuda.ipc_collect()

        except Exception:

            pass


# ============================================================
# LOAD FRESH QALB MODEL
# ============================================================

def load_fresh_model():

    print("\nLoading FRESH Qalb model...")

    print(
        f"Model: {MODEL_ID}"
    )

    # --------------------------------------------------------
    # MODEL
    # --------------------------------------------------------

    model = AutoModelForCausalLM.from_pretrained(

        MODEL_ID,

        quantization_config=bnb_config,

        device_map="auto",

        trust_remote_code=False,
    )

    # --------------------------------------------------------
    # TOKENIZER
    # --------------------------------------------------------

    tokenizer = AutoTokenizer.from_pretrained(

        MODEL_ID,

        trust_remote_code=False,
    )

    # --------------------------------------------------------
    # PAD TOKEN
    # --------------------------------------------------------

    if tokenizer.pad_token is None:

        tokenizer.pad_token = tokenizer.eos_token

    model.config.pad_token_id = tokenizer.pad_token_id

    # --------------------------------------------------------
    # PREPARE 4-BIT MODEL FOR TRAINING
    # --------------------------------------------------------

    model = prepare_model_for_kbit_training(
        model
    )

    # --------------------------------------------------------
    # LoRA
    # --------------------------------------------------------

    lora_config = LoraConfig(

        r=LORA_R,

        lora_alpha=LORA_ALPHA,

        lora_dropout=LORA_DROPOUT,

        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],

        bias="none",

        task_type="CAUSAL_LM",
    )

    model = get_peft_model(

        model,

        lora_config,
    )

    # --------------------------------------------------------
    # TRAINABLE PARAMETERS
    # --------------------------------------------------------

    model.print_trainable_parameters()

    print_memory(
        "MEMORY AFTER MODEL LOAD"
    )

    return model, tokenizer


# ============================================================
# BUILD USER CONTENT
# ============================================================

def build_user_content(
    row,
    input_columns,
):

    parts = []

    for col in input_columns:

        value = row[col]

        if pd.isna(value):

            value = ""

        value = str(value).strip()

        parts.append(
            f'{col}: "{value}"'
        )

    return "\n\n".join(parts)


# ============================================================
# QALB CHAT FORMATTING
# ============================================================
#
# This is the ONLY model-specific change.
#
# Your earlier Qalb few-shot code used:
#
# try:
#     tokenizer.apply_chat_template(...)
# except Exception:
#     text_in = f"{system}\n{user}\n"
#
# Since Qalb tokenizer has no chat_template, we directly use
# the same plain-text format here.
#
# ============================================================

def format_qalb_prompt(
    system_content,
    user_content,
):

    return (
        f"{system_content}\n"
        f"{user_content}\n"
    )


def format_qalb_training_example(
    system_content,
    user_content,
    assistant_content,
):

    return (
        f"{system_content}\n"
        f"{user_content}\n"
        f"{assistant_content}"
    )


# ============================================================
# PREPARE SFT DATA
# ============================================================
#
# TRAINING FORMAT:
#
# SYSTEM
# USER
# ASSISTANT = GOLD RESPONSE
#
# Loss is calculated ONLY on the response.
#
# ============================================================

def prepare_training_dataset(
    df,
    input_columns,
    tokenizer,
):

    dataset = []

    max_total_tokens = 0

    max_response_tokens = 0

    print(
        "\nBuilding training examples..."
    )

    for _, row in tqdm(

        df.iterrows(),

        total=len(df),

        desc="Preparing SFT data",

    ):

        # ----------------------------------------------------
        # USER INPUT
        # ----------------------------------------------------

        user_content = build_user_content(

            row,

            input_columns,
        )

        # ----------------------------------------------------
        # GOLD RESPONSE
        # ----------------------------------------------------

        gold_response = row[
            "Gold Response"
        ]

        if pd.isna(gold_response):

            gold_response = ""

        gold_response = str(
            gold_response
        ).strip()

        # ----------------------------------------------------
        # PROMPT ONLY
        # ----------------------------------------------------

        prompt_text = format_qalb_prompt(

            SYSTEM_INSTRUCTION,

            user_content,
        )

        # ----------------------------------------------------
        # FULL TRAINING EXAMPLE
        # ----------------------------------------------------

        full_text = format_qalb_training_example(

            SYSTEM_INSTRUCTION,

            user_content,

            gold_response,
        )

        # ----------------------------------------------------
        # TOKENIZE PROMPT
        # ----------------------------------------------------

        prompt_tokens = tokenizer(

            prompt_text,

            add_special_tokens=False,

        )["input_ids"]

        prompt_length = len(
            prompt_tokens
        )

        # ----------------------------------------------------
        # TOKENIZE FULL SEQUENCE
        # ----------------------------------------------------

        full_tokens = tokenizer(

            full_text,

            add_special_tokens=False,

            truncation=True,

            max_length=MAX_LENGTH,
        )

        input_ids = full_tokens[
            "input_ids"
        ]

        attention_mask = full_tokens[
            "attention_mask"
        ]

        # ----------------------------------------------------
        # LABELS
        #
        # Prompt tokens = -100
        #
        # Gold response tokens = actual token IDs
        #
        # Therefore loss is only calculated on response.
        # ----------------------------------------------------

        labels = []

        for token_index in range(
            len(input_ids)
        ):

            if token_index < prompt_length:

                labels.append(-100)

            else:

                labels.append(
                    input_ids[token_index]
                )

        # ----------------------------------------------------
        # STATISTICS
        # ----------------------------------------------------

        response_length = max(

            0,

            len(input_ids) - prompt_length
        )

        max_total_tokens = max(

            max_total_tokens,

            len(input_ids)
        )

        max_response_tokens = max(

            max_response_tokens,

            response_length
        )

        # ----------------------------------------------------
        # ADD EXAMPLE
        # ----------------------------------------------------

        dataset.append({

            "input_ids": input_ids,

            "attention_mask": attention_mask,

            "labels": labels,

        })

    # --------------------------------------------------------
    # PRINT STATISTICS
    # --------------------------------------------------------

    print(
        f"\nTraining examples : "
        f"{len(dataset)}"
    )

    print(
        f"Maximum total tokens : "
        f"{max_total_tokens}"
    )

    print(
        f"Maximum response tokens : "
        f"{max_response_tokens}"
    )

    print(
        f"MAX_LENGTH : "
        f"{MAX_LENGTH}"
    )

    return dataset


# ============================================================
# PYTORCH DATASET
# ============================================================

class SFTDataset(
    torch.utils.data.Dataset
):

    def __init__(
        self,
        data,
    ):

        self.data = data

    def __len__(self):

        return len(self.data)

    def __getitem__(
        self,
        idx,
    ):

        return self.data[idx]


# ============================================================
# GENERATE TEST RESPONSES
# ============================================================

def generate_test_responses(

    model,

    tokenizer,

    test_df,

    input_columns,

    output_path,

):

    model.eval()

    responses = []

    max_tokens_seen = 0

    print(
        "\n================================================"
    )

    print(
        "GENERATING TEST RESPONSES"
    )

    print(
        f"Input columns: {input_columns}"
    )

    print(
        f"Test samples: {len(test_df)}"
    )

    print(
        "================================================\n"
    )

    for i, row in tqdm(

        test_df.iterrows(),

        total=len(test_df),

        desc="Generation",

    ):

        # ----------------------------------------------------
        # BUILD INPUT
        # ----------------------------------------------------

        user_content = build_user_content(

            row,

            input_columns,
        )

        # ----------------------------------------------------
        # QALB PROMPT FORMAT
        # ----------------------------------------------------

        text_in = format_qalb_prompt(

            SYSTEM_INSTRUCTION,

            user_content,
        )

        # ----------------------------------------------------
        # TOKEN COUNT
        # ----------------------------------------------------

        num_tokens = len(

            tokenizer(
                text_in
            )["input_ids"]
        )

        max_tokens_seen = max(

            max_tokens_seen,

            num_tokens,
        )

        # ----------------------------------------------------
        # TOKENIZE
        # ----------------------------------------------------

        inputs = tokenizer(

            text_in,

            return_tensors="pt",

            truncation=True,

            max_length=MAX_LENGTH,
        )

        # ----------------------------------------------------
        # MOVE INPUTS TO MODEL DEVICE
        # ----------------------------------------------------

        inputs = {
            key: value.to(model.device)
            for key, value in inputs.items()
        }

        # ----------------------------------------------------
        # GENERATION
        # ----------------------------------------------------

        with torch.no_grad():

            if i % 10 == 0:

                print(

                    f"\nBefore generate : "

                    f"{torch.cuda.memory_allocated()/1024**3:.2f} GB allocated | "

                    f"{torch.cuda.memory_reserved()/1024**3:.2f} GB reserved"
                )

            outputs = model.generate(

                **inputs,

                max_new_tokens=MAX_NEW_TOKENS,

                temperature=0.3,

                do_sample=True,

                repetition_penalty=1.1,

                pad_token_id=
                    tokenizer.eos_token_id,

                use_cache=True,
            )

            if i % 10 == 0:

                print(

                    f"After generate  : "

                    f"{torch.cuda.memory_allocated()/1024**3:.2f} GB allocated | "

                    f"{torch.cuda.memory_reserved()/1024**3:.2f} GB reserved"
                )

        # ----------------------------------------------------
        # REMOVE INPUT TOKENS
        # ----------------------------------------------------

        new_tokens = outputs[

            0

        ][

            inputs["input_ids"].shape[1]:
        ]

        # ----------------------------------------------------
        # DECODE RESPONSE
        # ----------------------------------------------------

        response = tokenizer.decode(

            new_tokens,

            skip_special_tokens=True,
        ).strip()

        responses.append(
            response
        )

        # ----------------------------------------------------
        # FREE MEMORY
        # ----------------------------------------------------

        del outputs

        del new_tokens

        del inputs

        gc.collect()

        torch.cuda.empty_cache()

        # ----------------------------------------------------
        # DIAGNOSTICS
        # ----------------------------------------------------

        if i % 10 == 0:

            print(
                "\n----------------------------------------"
            )

            print(
                f"Sample         : {i}"
            )

            print(
                f"Prompt Tokens  : {num_tokens}"
            )

            print(
                f"Maximum So Far : {max_tokens_seen}"
            )

            print(
                f"Allocated VRAM : "
                f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
            )

            print(
                f"Reserved VRAM  : "
                f"{torch.cuda.memory_reserved()/1024**3:.2f} GB"
            )

            print(
                "----------------------------------------"
            )

        # ----------------------------------------------------
        # BACKUP EVERY 25 SAMPLES
        # ----------------------------------------------------

        if i % 25 == 0 and i > 0:

            backup = test_df.copy()

            backup[
                "Qalb_Response"
            ] = (

                responses
                + [""] * (

                    len(test_df)
                    - len(responses)
                )
            )

            backup.to_csv(

                output_path.replace(

                    ".csv",

                    "_backup.csv",
                ),

                index=False,

                encoding="utf-8-sig",
            )

    # ========================================================
    # FINAL SAVE
    # ========================================================

    result = test_df.copy()

    result[
        "Qalb_Response"
    ] = responses

    result.to_csv(

        output_path,

        index=False,

        encoding="utf-8-sig",
    )

    print(
        f"\nSaved -> {output_path}"
    )

    return result


# ============================================================
# RUN ONE COMPLETE SFT EXPERIMENT
# ============================================================

def run_sft_experiment(

    experiment_name,

    input_columns,

    output_path,
):

    print("\n\n")

    print("=" * 75)

    print(
        f"STARTING SFT EXPERIMENT: "
        f"{experiment_name}"
    )

    print(
        f"INPUT COLUMNS: "
        f"{input_columns}"
    )

    print(
        f"EPOCHS: "
        f"{NUM_EPOCHS}"
    )

    print("=" * 75)

    # --------------------------------------------------------
    # CLEAN GPU
    # --------------------------------------------------------

    cleanup_gpu()

    torch.cuda.reset_peak_memory_stats()

    print_memory(
        "MEMORY BEFORE MODEL LOAD"
    )

    # --------------------------------------------------------
    # FRESH MODEL
    # --------------------------------------------------------

    model, tokenizer = (
        load_fresh_model()
    )

    # --------------------------------------------------------
    # PREPARE TRAIN DATA
    # --------------------------------------------------------

    train_data = (
        prepare_training_dataset(

            train_df,

            input_columns,

            tokenizer,
        )
    )

    train_dataset = SFTDataset(
        train_data
    )

    # --------------------------------------------------------
    # DATA COLLATOR
    # --------------------------------------------------------

    data_collator = DataCollatorForSeq2Seq(

        tokenizer=tokenizer,

        padding=True,

        return_tensors="pt",
    )

    print_memory(
        "MEMORY BEFORE TRAINING"
    )

    # --------------------------------------------------------
    # TRAINING ARGUMENTS
    # --------------------------------------------------------

    training_args = TrainingArguments(

        output_dir=(
            f"./sft_{experiment_name}"
        ),

        num_train_epochs=NUM_EPOCHS,

        per_device_train_batch_size=
            BATCH_SIZE,

        gradient_accumulation_steps=
            GRADIENT_ACCUMULATION,

        learning_rate=
            LEARNING_RATE,

        fp16=True,

        optim="paged_adamw_8bit",

        logging_steps=1,

        save_strategy="no",

        report_to="none",

        remove_unused_columns=False,

        gradient_checkpointing=True,

        max_grad_norm=0.3,

        warmup_ratio=0.03,

        lr_scheduler_type="cosine",
    )

    # --------------------------------------------------------
    # TRAINER
    # --------------------------------------------------------

    trainer = Trainer(

        model=model,

        args=training_args,

        train_dataset=train_dataset,

        data_collator=data_collator,
    )

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    print("\n")

    print(
        "================================================"
    )

    print(
        f"TRAINING {experiment_name}"
    )

    print(
        "================================================"
    )

    start_time = time.time()

    trainer.train()

    training_time = (
        time.time()
        - start_time
    )

    print(
        "\n================================================"
    )

    print(
        "TRAINING COMPLETE"
    )

    print(
        f"Training time: "
        f"{training_time / 60:.2f} minutes"
    )

    print(
        "================================================"
    )

    print_memory(
        "MEMORY AFTER TRAINING"
    )

    # --------------------------------------------------------
    # GENERATE TEST
    # --------------------------------------------------------

    result = generate_test_responses(

        model=model,

        tokenizer=tokenizer,

        test_df=test_df,

        input_columns=input_columns,

        output_path=output_path,
    )

    # --------------------------------------------------------
    # CLEANUP
    # --------------------------------------------------------

    print(
        "\nCleaning up model..."
    )

    del trainer

    del model

    del tokenizer

    del train_dataset

    del train_data

    cleanup_gpu()

    print_memory(
        "FINAL MEMORY AFTER CLEANUP"
    )

    return result


# ============================================================
# EXPERIMENT 1
# U
# ============================================================

result_U = run_sft_experiment(

    experiment_name="U",

    input_columns=[
        "User Utterance"
    ],

    output_path=(
        r"51_SFT_U_Qalb_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 2
# U + CONTEXT
# ============================================================

result_UC = run_sft_experiment(

    experiment_name="U_C",

    input_columns=[
        "User Utterance",
        "Context",
    ],

    output_path=(
        r"51_SFT_U_C_Qalb_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 3
# U + CONTEXT + ROLES
# ============================================================

result_UCR = run_sft_experiment(

    experiment_name="U_C_R",

    input_columns=[
        "User Utterance",
        "Context",
        "User Role",
        "Model Role",
    ],

    output_path=(
        r"51_SFT_U_C_R_Qalb_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 4
# U + CONTEXT + ROLES + POWER DISTANCE
# ============================================================

result_UCRPD = run_sft_experiment(

    experiment_name="U_C_R_PD",

    input_columns=[
        "User Utterance",
        "Context",
        "User Role",
        "Model Role",
        "Power Distance",
    ],

    output_path=(
        r"51_SFT_U_C_R_PD_Qalb_test.csv"
    ),
)


# ============================================================
# DONE
# ============================================================

print("\n\n")

print("=" * 75)

print(
    "ALL FOUR QALB SFT EXPERIMENTS COMPLETED"
)

print("=" * 75)

print(
    "\nGenerated files:"
)

print(
    r"1. 51_SFT_U_Qalb_test.csv"
)

print(
    r"2. 51_SFT_U_C_Qalb_test.csv"
)

print(
    r"3. 51_SFT_U_C_R_Qalb_test.csv"
)

print(
    r"4. 51_SFT_U_C_R_PD_Qalb_test.csv"
)

print("=" * 75)

D:\stdFurqan\FYP_AA\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

==============================================
DATASET
==============================================
Train shape : (51, 11)
Test shape  : (255, 11)

Columns:
['Language', 'Topic', 'User Role', 'Model Role', 'Power Distance', 'Register', 'Pragmatic Genre', 'Sensitivity', 'User Utterance', 'Context', 'Gold Response']

==============================================


================ GPU INFO ================
GPU : NVIDIA GeForce RTX 4080 SUPER
Total VRAM : 15.99 GB
Allocated : 0.00 GB
Reserved  : 0.00 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U
INPUT COLUMNS: ['User Utterance']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 0.00 GB
Reserved  : 0.00 GB
Max Allocated : 0.00 GB
Max Reserved  : 0.00 GB
==========================================


Loading FRESH Qalb model...
Model: enstazao/Qalb-1.0-8B-Instruct

Loading weights: 100%|██████████| 291/291 [00:04<00:00, 63.43it/s]

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

================ MEMORY AFTER MODEL LOAD ================
Allocated : 7.43 GB
Reserved  : 9.51 GB
Max Allocated : 8.25 GB
Max Reserved  : 9.51 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 51/51 [00:00<00:00, 3090.11it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 51
Maximum total tokens : 203
Maximum response tokens : 88
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 7.43 GB
Reserved  : 9.51 GB
Max Allocated : 8.25 GB
Max Reserved  : 9.51 GB
==========================================



================================================
TRAINING U
================================================

================================================
TRAINING COMPLETE
Training time: 3.54 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 7.48 GB
Reserved  : 9.80 GB
Max Allocated : 9.04 GB
Max Reserved  : 9.80 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.80 GB reserved

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

After generate  : 7.48 GB allocated | 9.80 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 66
Maximum So Far : 66
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:   0%|          | 1/255 [00:02<11:47,  2.79s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   1%|          | 2/255 [00:05<11:30,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   1%|          | 3/255 [00:08<11:18,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 4/255 [00:10<11:12,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 5/255 [00:13<11:09,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 6/255 [00:16<11:04,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   3%|▎         | 7/255 [00:18<11:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   3%|▎         | 8/255 [00:21<10:57,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   4%|▎         | 9/255 [00:24<10:57,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   4%|▍         | 10/255 [00:26<10:53,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 68
Maximum So Far : 80
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:   4%|▍         | 11/255 [00:29<10:49,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▍         | 12/255 [00:32<10:46,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▌         | 13/255 [00:34<10:45,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▌         | 14/255 [00:37<10:41,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   6%|▌         | 15/255 [00:40<10:37,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   6%|▋         | 16/255 [00:42<10:35,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 17/255 [00:45<10:36,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 18/255 [00:48<10:31,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 19/255 [00:50<10:28,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   8%|▊         | 20/255 [00:53<10:26,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 65
Maximum So Far : 80
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:   8%|▊         | 21/255 [00:56<10:24,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▊         | 22/255 [00:58<10:20,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▉         | 23/255 [01:01<10:15,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▉         | 24/255 [01:04<10:14,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  10%|▉         | 25/255 [01:06<10:10,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  10%|█         | 26/255 [01:09<10:07,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█         | 27/255 [01:11<10:03,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█         | 28/255 [01:14<10:05,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█▏        | 29/255 [01:17<10:00,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  12%|█▏        | 30/255 [01:19<09:56,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 54
Maximum So Far : 87
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  12%|█▏        | 31/255 [01:22<09:54,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 32/255 [01:25<09:53,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 33/255 [01:27<09:48,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 34/255 [01:30<09:45,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  14%|█▎        | 35/255 [01:33<09:41,  2.64s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  14%|█▍        | 36/255 [01:35<09:41,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▍        | 37/255 [01:38<09:37,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▍        | 38/255 [01:41<09:33,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▌        | 39/255 [01:43<09:31,  2.64s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  16%|█▌        | 40/255 [01:46<09:30,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 74
Maximum So Far : 87
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  16%|█▌        | 41/255 [01:49<09:25,  2.64s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  16%|█▋        | 42/255 [01:51<09:22,  2.64s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  17%|█▋        | 43/255 [01:54<09:22,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  17%|█▋        | 44/255 [01:57<09:18,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 45/255 [01:59<09:16,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 46/255 [02:02<09:13,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 47/255 [02:04<09:11,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  19%|█▉        | 48/255 [02:07<09:07,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  19%|█▉        | 49/255 [02:10<09:05,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  20%|█▉        | 50/255 [02:12<09:03,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 54
Maximum So Far : 87
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  20%|██        | 51/255 [02:15<09:03,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  20%|██        | 52/255 [02:18<09:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  21%|██        | 53/255 [02:20<08:57,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  21%|██        | 54/255 [02:23<08:54,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 55/255 [02:26<08:53,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 56/255 [02:28<08:50,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 57/255 [02:31<08:48,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  23%|██▎       | 58/255 [02:34<08:46,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  23%|██▎       | 59/255 [02:37<08:46,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  24%|██▎       | 60/255 [02:39<08:43,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 60
Maximum So Far : 87
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  24%|██▍       | 61/255 [02:42<08:40,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  24%|██▍       | 62/255 [02:45<08:39,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▍       | 63/255 [02:47<08:36,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▌       | 64/255 [02:50<08:32,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▌       | 65/255 [02:53<08:29,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  26%|██▌       | 66/255 [02:55<08:29,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  26%|██▋       | 67/255 [02:58<08:26,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 68/255 [03:01<08:23,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 69/255 [03:03<08:20,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 70/255 [03:06<08:19,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 80
Maximum So Far : 87
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  28%|██▊       | 71/255 [03:09<08:16,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  28%|██▊       | 72/255 [03:12<08:12,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▊       | 73/255 [03:14<08:09,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▉       | 74/255 [03:17<08:08,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▉       | 75/255 [03:20<08:04,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  30%|██▉       | 76/255 [03:22<08:01,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  30%|███       | 77/255 [03:25<08:00,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███       | 78/255 [03:28<07:57,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███       | 79/255 [03:30<07:53,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███▏      | 80/255 [03:33<07:49,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 61
Maximum So Far : 87
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  32%|███▏      | 81/255 [03:36<07:47,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  32%|███▏      | 82/255 [03:38<07:44,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 83/255 [03:41<07:40,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 84/255 [03:44<07:37,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 85/255 [03:46<07:36,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  34%|███▎      | 86/255 [03:49<07:32,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  34%|███▍      | 87/255 [03:52<07:28,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▍      | 88/255 [03:54<07:25,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▍      | 89/255 [03:57<07:25,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▌      | 90/255 [04:00<07:21,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 57
Maximum So Far : 87
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  36%|███▌      | 91/255 [04:02<07:18,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  36%|███▌      | 92/255 [04:05<07:16,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  36%|███▋      | 93/255 [04:08<07:12,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  37%|███▋      | 94/255 [04:10<07:10,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  37%|███▋      | 95/255 [04:13<07:07,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 96/255 [04:16<07:06,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 97/255 [04:19<07:02,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 98/255 [04:21<06:59,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  39%|███▉      | 99/255 [04:24<06:55,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  39%|███▉      | 100/255 [04:27<06:54,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 63
Maximum So Far : 87
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  40%|███▉      | 101/255 [04:29<06:52,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  40%|████      | 102/255 [04:32<06:48,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  40%|████      | 103/255 [04:35<06:45,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  41%|████      | 104/255 [04:37<06:44,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  41%|████      | 105/255 [04:40<06:40,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 106/255 [04:43<06:36,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 107/255 [04:45<06:34,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 108/255 [04:48<06:33,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  43%|████▎     | 109/255 [04:51<06:29,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  43%|████▎     | 110/255 [04:53<06:26,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved

Generation:  44%|████▎     | 111/255 [04:56<06:26,  2.68s/it]

After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 66
Maximum So Far : 89
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

[transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  44%|████▍     | 112/255 [04:59<06:22,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  44%|████▍     | 113/255 [05:01<06:18,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▍     | 114/255 [05:04<06:14,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▌     | 115/255 [05:07<06:13,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▌     | 116/255 [05:09<06:10,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  46%|████▌     | 117/255 [05:12<06:07,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  46%|████▋     | 118/255 [05:15<06:04,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  47%|████▋     | 119/255 [05:17<06:03,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  47%|████▋     | 120/255 [05:20<05:59,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 73
Maximum So Far : 89
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  47%|████▋     | 121/255 [05:23<05:56,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  48%|████▊     | 122/255 [05:25<05:53,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  48%|████▊     | 123/255 [05:28<05:52,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▊     | 124/255 [05:31<05:49,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▉     | 125/255 [05:33<05:45,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▉     | 126/255 [05:36<05:42,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  50%|████▉     | 127/255 [05:39<05:41,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  50%|█████     | 128/255 [05:41<05:38,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  51%|█████     | 129/255 [05:44<05:35,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  51%|█████     | 130/255 [05:47<05:33,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 76
Maximum So Far : 89
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  51%|█████▏    | 131/255 [05:49<05:31,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  52%|█████▏    | 132/255 [05:52<05:28,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  52%|█████▏    | 133/255 [05:55<05:24,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 134/255 [05:57<05:23,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 135/255 [06:00<05:20,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 136/255 [06:03<05:16,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  54%|█████▎    | 137/255 [06:05<05:14,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  54%|█████▍    | 138/255 [06:08<05:12,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  55%|█████▍    | 139/255 [06:11<05:08,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  55%|█████▍    | 140/255 [06:13<05:06,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 65
Maximum So Far : 89
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  55%|█████▌    | 141/255 [06:16<05:03,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▌    | 142/255 [06:19<05:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▌    | 143/255 [06:21<04:58,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▋    | 144/255 [06:24<04:55,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  57%|█████▋    | 145/255 [06:26<04:51,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  57%|█████▋    | 146/255 [06:29<04:50,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 147/255 [06:32<04:47,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 148/255 [06:34<04:44,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 149/255 [06:37<04:43,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  59%|█████▉    | 150/255 [06:40<04:40,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 76
Maximum So Far : 89
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  59%|█████▉    | 151/255 [06:42<04:37,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|█████▉    | 152/255 [06:45<04:34,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|██████    | 153/255 [06:48<04:32,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|██████    | 154/255 [06:50<04:29,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  61%|██████    | 155/255 [06:53<04:26,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  61%|██████    | 156/255 [06:56<04:23,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 157/255 [06:59<04:21,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 158/255 [07:01<04:18,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 159/255 [07:04<04:15,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  63%|██████▎   | 160/255 [07:06<04:12,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved

Generation:  63%|██████▎   | 161/255 [07:09<04:11,  2.68s/it]

After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 80
Maximum So Far : 89
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

[transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▎   | 162/255 [07:12<04:08,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▍   | 163/255 [07:14<04:05,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▍   | 164/255 [07:17<04:02,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▍   | 165/255 [07:20<04:00,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▌   | 166/255 [07:22<03:57,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▌   | 167/255 [07:25<03:54,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  66%|██████▌   | 168/255 [07:28<03:52,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  66%|██████▋   | 169/255 [07:31<03:50,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  67%|██████▋   | 170/255 [07:33<03:46,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 71
Maximum So Far : 91
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  67%|██████▋   | 171/255 [07:36<03:43,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  67%|██████▋   | 172/255 [07:39<03:41,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  68%|██████▊   | 173/255 [07:41<03:39,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  68%|██████▊   | 174/255 [07:44<03:35,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▊   | 175/255 [07:47<03:33,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▉   | 176/255 [07:49<03:31,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▉   | 177/255 [07:52<03:27,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  70%|██████▉   | 178/255 [07:55<03:24,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  70%|███████   | 179/255 [07:57<03:21,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  71%|███████   | 180/255 [08:00<03:20,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 66
Maximum So Far : 91
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  71%|███████   | 181/255 [08:03<03:17,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  71%|███████▏  | 182/255 [08:05<03:14,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  72%|███████▏  | 183/255 [08:08<03:11,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  72%|███████▏  | 184/255 [08:10<03:08,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 185/255 [08:13<03:06,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 186/255 [08:16<03:03,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 187/255 [08:18<03:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  74%|███████▎  | 188/255 [08:21<02:58,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  74%|███████▍  | 189/255 [08:24<02:55,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  75%|███████▍  | 190/255 [08:26<02:52,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 66
Maximum So Far : 91
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  75%|███████▍  | 191/255 [08:29<02:51,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  75%|███████▌  | 192/255 [08:32<02:47,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▌  | 193/255 [08:34<02:45,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▌  | 194/255 [08:37<02:42,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▋  | 195/255 [08:40<02:40,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  77%|███████▋  | 196/255 [08:42<02:36,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  77%|███████▋  | 197/255 [08:45<02:34,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 198/255 [08:48<02:31,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 199/255 [08:50<02:29,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 200/255 [08:53<02:27,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 80
Maximum So Far : 100
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  79%|███████▉  | 201/255 [08:56<02:24,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  79%|███████▉  | 202/255 [08:59<02:22,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|███████▉  | 203/255 [09:01<02:19,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|████████  | 204/255 [09:04<02:16,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|████████  | 205/255 [09:07<02:13,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  81%|████████  | 206/255 [09:09<02:11,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  81%|████████  | 207/255 [09:12<02:08,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 208/255 [09:15<02:05,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 209/255 [09:17<02:03,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 210/255 [09:20<02:01,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 57
Maximum So Far : 100
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  83%|████████▎ | 211/255 [09:23<01:58,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  83%|████████▎ | 212/255 [09:25<01:55,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▎ | 213/255 [09:28<01:52,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▍ | 214/255 [09:31<01:50,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▍ | 215/255 [09:33<01:47,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▍ | 216/255 [09:36<01:44,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▌ | 217/255 [09:39<01:42,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▌ | 218/255 [09:42<01:39,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  86%|████████▌ | 219/255 [09:44<01:37,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  86%|████████▋ | 220/255 [09:47<01:34,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 54
Maximum So Far : 100
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  87%|████████▋ | 221/255 [09:50<01:31,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  87%|████████▋ | 222/255 [09:52<01:29,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  87%|████████▋ | 223/255 [09:55<01:26,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  88%|████████▊ | 224/255 [09:58<01:23,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  88%|████████▊ | 225/255 [10:00<01:20,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▊ | 226/255 [10:03<01:18,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▉ | 227/255 [10:06<01:15,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▉ | 228/255 [10:09<01:13,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  90%|████████▉ | 229/255 [10:11<01:10,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  90%|█████████ | 230/255 [10:14<01:07,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 83
Maximum So Far : 100
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  91%|█████████ | 231/255 [10:17<01:04,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  91%|█████████ | 232/255 [10:19<01:02,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  91%|█████████▏| 233/255 [10:22<00:59,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  92%|█████████▏| 234/255 [10:25<00:56,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  92%|█████████▏| 235/255 [10:27<00:53,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 236/255 [10:30<00:51,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 237/255 [10:33<00:48,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 238/255 [10:35<00:45,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  94%|█████████▎| 239/255 [10:38<00:42,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  94%|█████████▍| 240/255 [10:41<00:39,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved
After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 76
Maximum So Far : 100
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

Generation:  95%|█████████▍| 241/255 [10:43<00:37,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  95%|█████████▍| 242/255 [10:46<00:34,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  95%|█████████▌| 243/255 [10:49<00:31,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▌| 244/255 [10:51<00:29,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▌| 245/255 [10:54<00:26,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▋| 246/255 [10:57<00:23,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  97%|█████████▋| 247/255 [10:59<00:21,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  97%|█████████▋| 248/255 [11:02<00:18,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  98%|█████████▊| 249/255 [11:05<00:16,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  98%|█████████▊| 250/255 [11:07<00:13,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 7.48 GB allocated | 9.63 GB reserved

Generation:  98%|█████████▊| 251/255 [11:10<00:10,  2.68s/it]

After generate  : 7.48 GB allocated | 9.63 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 79
Maximum So Far : 100
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.63 GB
----------------------------------------

[transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  99%|█████████▉| 252/255 [11:13<00:08,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  99%|█████████▉| 253/255 [11:15<00:05,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation: 100%|█████████▉| 254/255 [11:18<00:02,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation: 100%|██████████| 255/255 [11:21<00:00,  2.67s/it]

Saved -> 51_SFT_U_Qalb_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 1.97 GB
Reserved  : 7.17 GB
Max Allocated : 9.04 GB
Max Reserved  : 9.80 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C
INPUT COLUMNS: ['User Utterance', 'Context']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 1.97 GB
Reserved  : 7.17 GB
Max Allocated : 1.97 GB
Max Reserved  : 7.17 GB
==========================================


Loading FRESH Qalb model...
Model: enstazao/Qalb-1.0-8B-Instruct

Loading weights: 100%|██████████| 291/291 [00:04<00:00, 63.58it/s]

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

================ MEMORY AFTER MODEL LOAD ================
Allocated : 9.40 GB
Reserved  : 11.48 GB
Max Allocated : 10.22 GB
Max Reserved  : 11.48 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 51/51 [00:00<00:00, 2548.06it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 51
Maximum total tokens : 290
Maximum response tokens : 88
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 9.40 GB
Reserved  : 11.48 GB
Max Allocated : 10.22 GB
Max Reserved  : 11.48 GB
==========================================



================================================
TRAINING U_C
================================================

================================================
TRAINING COMPLETE
Training time: 3.88 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 9.44 GB
Reserved  : 11.76 GB
Max Allocated : 11.15 GB
Max Reserved  : 11.76 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.76 GB reserved
After generate  : 9.44 GB allocated | 11.76 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 120
Maximum So Far : 120
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:   0%|          | 1/255 [00:02<11:16,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   1%|          | 2/255 [00:05<11:09,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   1%|          | 3/255 [00:07<11:11,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 4/255 [00:10<11:09,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 5/255 [00:13<11:04,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 6/255 [00:15<11:03,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   3%|▎         | 7/255 [00:18<11:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   3%|▎         | 8/255 [00:21<10:57,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   4%|▎         | 9/255 [00:23<10:53,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   4%|▍         | 10/255 [00:26<10:53,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 124
Maximum So Far : 148
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:   4%|▍         | 11/255 [00:29<10:49,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▍         | 12/255 [00:31<10:44,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▌         | 13/255 [00:34<10:42,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▌         | 14/255 [00:37<10:41,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   6%|▌         | 15/255 [00:39<10:39,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   6%|▋         | 16/255 [00:42<10:36,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 17/255 [00:45<10:35,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 18/255 [00:47<10:31,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 19/255 [00:50<10:27,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   8%|▊         | 20/255 [00:53<10:26,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 140
Maximum So Far : 150
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:   8%|▊         | 21/255 [00:55<10:26,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▊         | 22/255 [00:58<10:25,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▉         | 23/255 [01:01<10:22,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▉         | 24/255 [01:04<10:21,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  10%|▉         | 25/255 [01:06<10:16,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  10%|█         | 26/255 [01:09<10:11,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█         | 27/255 [01:12<10:08,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█         | 28/255 [01:14<10:07,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█▏        | 29/255 [01:17<10:04,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  12%|█▏        | 30/255 [01:20<09:59,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 119
Maximum So Far : 170
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  12%|█▏        | 31/255 [01:22<09:55,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 32/255 [01:25<09:53,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 33/255 [01:27<09:50,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 34/255 [01:30<09:48,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  14%|█▎        | 35/255 [01:33<09:44,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  14%|█▍        | 36/255 [01:35<09:44,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▍        | 37/255 [01:38<09:46,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▍        | 38/255 [01:41<09:42,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▌        | 39/255 [01:44<09:38,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  16%|█▌        | 40/255 [01:46<09:38,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 122
Maximum So Far : 170
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  16%|█▌        | 41/255 [01:49<09:45,  2.74s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  16%|█▋        | 42/255 [01:52<09:38,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  17%|█▋        | 43/255 [01:54<09:32,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  17%|█▋        | 44/255 [01:57<09:32,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 45/255 [02:00<09:25,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 46/255 [02:03<09:21,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 47/255 [02:05<09:17,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  19%|█▉        | 48/255 [02:08<09:16,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  19%|█▉        | 49/255 [02:11<09:11,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  20%|█▉        | 50/255 [02:13<09:10,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 105
Maximum So Far : 170
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  20%|██        | 51/255 [02:16<09:06,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  20%|██        | 52/255 [02:19<09:06,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  21%|██        | 53/255 [02:21<09:03,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  21%|██        | 54/255 [02:24<08:59,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 55/255 [02:27<08:55,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 56/255 [02:29<09:02,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 57/255 [02:32<08:56,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  23%|██▎       | 58/255 [02:35<08:54,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  23%|██▎       | 59/255 [02:38<08:49,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  24%|██▎       | 60/255 [02:40<08:46,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 100
Maximum So Far : 170
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  24%|██▍       | 61/255 [02:43<08:42,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  24%|██▍       | 62/255 [02:46<08:37,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▍       | 63/255 [02:48<08:35,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▌       | 64/255 [02:51<08:36,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▌       | 65/255 [02:54<08:34,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  26%|██▌       | 66/255 [02:56<08:31,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  26%|██▋       | 67/255 [02:59<08:29,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 68/255 [03:02<08:25,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 69/255 [03:05<08:24,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 70/255 [03:07<08:20,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 141
Maximum So Far : 170
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  28%|██▊       | 71/255 [03:10<08:16,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  28%|██▊       | 72/255 [03:13<08:14,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▊       | 73/255 [03:15<08:12,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▉       | 74/255 [03:18<08:08,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▉       | 75/255 [03:21<08:05,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  30%|██▉       | 76/255 [03:24<08:10,  2.74s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  30%|███       | 77/255 [03:26<08:06,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███       | 78/255 [03:29<08:03,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███       | 79/255 [03:32<07:58,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███▏      | 80/255 [03:34<07:53,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 151
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  32%|███▏      | 81/255 [03:37<07:48,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  32%|███▏      | 82/255 [03:40<07:46,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 83/255 [03:42<07:42,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 84/255 [03:45<07:39,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 85/255 [03:48<07:36,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  34%|███▎      | 86/255 [03:50<07:33,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  34%|███▍      | 87/255 [03:53<07:31,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▍      | 88/255 [03:56<07:33,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▍      | 89/255 [03:59<07:35,  2.74s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▌      | 90/255 [04:01<07:29,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 119
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  36%|███▌      | 91/255 [04:04<07:24,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  36%|███▌      | 92/255 [04:07<07:20,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  36%|███▋      | 93/255 [04:10<07:18,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  37%|███▋      | 94/255 [04:12<07:14,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  37%|███▋      | 95/255 [04:15<07:10,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 96/255 [04:19<07:59,  3.02s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 97/255 [04:21<07:40,  2.92s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 98/255 [04:24<07:27,  2.85s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  39%|███▉      | 99/255 [04:27<07:19,  2.82s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  39%|███▉      | 100/255 [04:29<07:09,  2.77s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 126
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  40%|███▉      | 101/255 [04:32<07:02,  2.75s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  40%|████      | 102/255 [04:35<06:56,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  40%|████      | 103/255 [04:37<06:53,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  41%|████      | 104/255 [04:40<06:49,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  41%|████      | 105/255 [04:43<06:50,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 106/255 [04:46<06:46,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 107/255 [04:48<06:42,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 108/255 [04:52<07:04,  2.89s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  43%|████▎     | 109/255 [04:54<06:53,  2.83s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  43%|████▎     | 110/255 [04:57<06:44,  2.79s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 116
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  44%|████▎     | 111/255 [05:00<06:38,  2.76s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  44%|████▍     | 112/255 [05:03<06:34,  2.76s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  44%|████▍     | 113/255 [05:05<06:27,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▍     | 114/255 [05:08<06:22,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▌     | 115/255 [05:11<06:20,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▌     | 116/255 [05:13<06:18,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  46%|████▌     | 117/255 [05:16<06:13,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  46%|████▋     | 118/255 [05:19<06:09,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  47%|████▋     | 119/255 [05:21<06:08,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  47%|████▋     | 120/255 [05:24<06:07,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 117
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  47%|████▋     | 121/255 [05:27<06:03,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  48%|████▊     | 122/255 [05:30<05:58,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  48%|████▊     | 123/255 [05:32<05:58,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▊     | 124/255 [05:35<05:54,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▉     | 125/255 [05:38<05:50,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▉     | 126/255 [05:40<05:47,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  50%|████▉     | 127/255 [05:43<05:46,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  50%|█████     | 128/255 [05:46<05:42,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  51%|█████     | 129/255 [05:48<05:38,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  51%|█████     | 130/255 [05:51<05:35,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 142
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  51%|█████▏    | 131/255 [05:54<05:35,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  52%|█████▏    | 132/255 [05:57<05:31,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  52%|█████▏    | 133/255 [05:59<05:28,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 134/255 [06:02<05:25,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 135/255 [06:05<05:22,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 136/255 [06:07<05:18,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  54%|█████▎    | 137/255 [06:10<05:15,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  54%|█████▍    | 138/255 [06:13<05:14,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  55%|█████▍    | 139/255 [06:15<05:11,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  55%|█████▍    | 140/255 [06:18<05:09,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 105
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  55%|█████▌    | 141/255 [06:21<05:06,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▌    | 142/255 [06:23<05:06,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▌    | 143/255 [06:26<05:02,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▋    | 144/255 [06:29<04:58,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  57%|█████▋    | 145/255 [06:31<04:56,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  57%|█████▋    | 146/255 [06:34<04:53,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 147/255 [06:37<04:50,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 148/255 [06:39<04:46,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 149/255 [06:42<04:45,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  59%|█████▉    | 150/255 [06:45<04:41,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 117
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  59%|█████▉    | 151/255 [06:48<04:38,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|█████▉    | 152/255 [06:50<04:36,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|██████    | 153/255 [06:53<04:34,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|██████    | 154/255 [06:56<04:31,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  61%|██████    | 155/255 [06:58<04:28,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  61%|██████    | 156/255 [07:01<04:26,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 157/255 [07:04<04:24,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 158/255 [07:06<04:22,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 159/255 [07:09<04:19,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  63%|██████▎   | 160/255 [07:12<04:15,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 141
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  63%|██████▎   | 161/255 [07:14<04:12,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▎   | 162/255 [07:17<04:10,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▍   | 163/255 [07:20<04:07,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▍   | 164/255 [07:23<04:04,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▍   | 165/255 [07:25<04:01,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▌   | 166/255 [07:28<03:59,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▌   | 167/255 [07:31<03:56,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  66%|██████▌   | 168/255 [07:33<03:53,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  66%|██████▋   | 169/255 [07:36<03:50,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  67%|██████▋   | 170/255 [07:39<03:47,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved

Generation:  67%|██████▋   | 171/255 [07:41<03:44,  2.67s/it]

After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 106
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

[transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  67%|██████▋   | 172/255 [07:44<03:41,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  68%|██████▊   | 173/255 [07:47<03:40,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  68%|██████▊   | 174/255 [07:49<03:37,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▊   | 175/255 [07:52<03:34,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▉   | 176/255 [07:55<03:31,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▉   | 177/255 [07:57<03:29,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  70%|██████▉   | 178/255 [08:00<03:27,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  70%|███████   | 179/255 [08:03<03:24,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  71%|███████   | 180/255 [08:05<03:21,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 111
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  71%|███████   | 181/255 [08:08<03:18,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  71%|███████▏  | 182/255 [08:11<03:16,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  72%|███████▏  | 183/255 [08:14<03:13,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  72%|███████▏  | 184/255 [08:16<03:11,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 185/255 [08:19<03:08,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 186/255 [08:22<03:05,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 187/255 [08:24<03:03,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  74%|███████▎  | 188/255 [08:27<03:00,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  74%|███████▍  | 189/255 [08:30<02:57,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  75%|███████▍  | 190/255 [08:32<02:54,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 104
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  75%|███████▍  | 191/255 [08:35<02:52,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  75%|███████▌  | 192/255 [08:38<02:48,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▌  | 193/255 [08:40<02:45,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▌  | 194/255 [08:43<02:43,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▋  | 195/255 [08:46<02:40,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  77%|███████▋  | 196/255 [08:48<02:37,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  77%|███████▋  | 197/255 [08:51<02:35,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 198/255 [08:54<02:32,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 199/255 [08:56<02:30,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 200/255 [08:59<02:26,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 136
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  79%|███████▉  | 201/255 [09:02<02:24,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  79%|███████▉  | 202/255 [09:04<02:21,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|███████▉  | 203/255 [09:07<02:19,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|████████  | 204/255 [09:10<02:15,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|████████  | 205/255 [09:12<02:12,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  81%|████████  | 206/255 [09:15<02:10,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  81%|████████  | 207/255 [09:18<02:07,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 208/255 [09:20<02:04,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 209/255 [09:23<02:01,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 210/255 [09:26<01:59,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 101
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  83%|████████▎ | 211/255 [09:28<01:56,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  83%|████████▎ | 212/255 [09:31<01:54,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▎ | 213/255 [09:34<01:51,  2.65s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▍ | 214/255 [09:36<01:49,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▍ | 215/255 [09:39<01:46,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▍ | 216/255 [09:42<01:43,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▌ | 217/255 [09:44<01:41,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▌ | 218/255 [09:47<01:38,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  86%|████████▌ | 219/255 [09:50<01:36,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  86%|████████▋ | 220/255 [09:52<01:33,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 94
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  87%|████████▋ | 221/255 [09:55<01:30,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  87%|████████▋ | 222/255 [09:58<01:28,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  87%|████████▋ | 223/255 [10:00<01:25,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  88%|████████▊ | 224/255 [10:03<01:22,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  88%|████████▊ | 225/255 [10:05<01:16,  2.54s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▊ | 226/255 [10:08<01:14,  2.58s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▉ | 227/255 [10:11<01:12,  2.60s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▉ | 228/255 [10:13<01:10,  2.62s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  90%|████████▉ | 229/255 [10:16<01:08,  2.64s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  90%|█████████ | 230/255 [10:19<01:06,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 139
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  91%|█████████ | 231/255 [10:21<01:04,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  91%|█████████ | 232/255 [10:24<01:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  91%|█████████▏| 233/255 [10:27<00:58,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  92%|█████████▏| 234/255 [10:30<01:02,  2.97s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  92%|█████████▏| 235/255 [10:33<00:58,  2.90s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 236/255 [10:36<00:54,  2.85s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 237/255 [10:39<00:50,  2.80s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 238/255 [10:41<00:47,  2.77s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  94%|█████████▎| 239/255 [10:44<00:43,  2.74s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  94%|█████████▍| 240/255 [10:47<00:40,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.58 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 125
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  95%|█████████▍| 241/255 [10:49<00:38,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  95%|█████████▍| 242/255 [10:52<00:35,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  95%|█████████▌| 243/255 [10:55<00:32,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▌| 244/255 [10:57<00:29,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▌| 245/255 [11:00<00:26,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▋| 246/255 [11:03<00:24,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  97%|█████████▋| 247/255 [11:06<00:22,  2.87s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  97%|█████████▋| 248/255 [11:09<00:19,  2.81s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  98%|█████████▊| 249/255 [11:11<00:16,  2.77s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  98%|█████████▊| 250/255 [11:14<00:13,  2.75s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 9.44 GB allocated | 11.58 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 144
Maximum So Far : 190
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.58 GB
----------------------------------------

Generation:  98%|█████████▊| 251/255 [11:17<00:10,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  99%|█████████▉| 252/255 [11:19<00:08,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  99%|█████████▉| 253/255 [11:22<00:05,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation: 100%|█████████▉| 254/255 [11:25<00:02,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation: 100%|██████████| 255/255 [11:27<00:00,  2.70s/it]

Saved -> 51_SFT_U_C_Qalb_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 3.93 GB
Reserved  : 9.12 GB
Max Allocated : 11.15 GB
Max Reserved  : 11.76 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C_R
INPUT COLUMNS: ['User Utterance', 'Context', 'User Role', 'Model Role']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 3.93 GB
Reserved  : 9.12 GB
Max Allocated : 3.93 GB
Max Reserved  : 9.12 GB
==========================================


Loading FRESH Qalb model...
Model: enstazao/Qalb-1.0-8B-Instruct

Loading weights: 100%|██████████| 291/291 [00:04<00:00, 63.54it/s]

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

================ MEMORY AFTER MODEL LOAD ================
Allocated : 11.36 GB
Reserved  : 13.43 GB
Max Allocated : 12.18 GB
Max Reserved  : 13.43 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 51/51 [00:00<00:00, 1676.96it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 51
Maximum total tokens : 305
Maximum response tokens : 88
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 11.36 GB
Reserved  : 13.43 GB
Max Allocated : 12.18 GB
Max Reserved  : 13.43 GB
==========================================



================================================
TRAINING U_C_R
================================================

================================================
TRAINING COMPLETE
Training time: 4.01 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 11.40 GB
Reserved  : 13.72 GB
Max Allocated : 13.13 GB
Max Reserved  : 13.72 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context', 'User Role', 'Model Role']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.72 GB reserved
After generate  : 11.40 GB allocated | 13.72 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 137
Maximum So Far : 137
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:   0%|          | 1/255 [00:02<11:43,  2.77s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   1%|          | 2/255 [00:05<11:30,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   1%|          | 3/255 [00:08<12:36,  3.00s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 4/255 [00:11<12:05,  2.89s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 5/255 [00:14<11:43,  2.81s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 6/255 [00:16<11:28,  2.77s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   3%|▎         | 7/255 [00:19<11:19,  2.74s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   3%|▎         | 8/255 [00:22<11:11,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   4%|▎         | 9/255 [00:24<11:04,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   4%|▍         | 10/255 [00:27<11:03,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 141
Maximum So Far : 166
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:   4%|▍         | 11/255 [00:30<10:57,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▍         | 12/255 [00:32<10:52,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▌         | 13/255 [00:35<10:48,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▌         | 14/255 [00:38<10:48,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   6%|▌         | 15/255 [00:41<10:44,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   6%|▋         | 16/255 [00:43<10:41,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 17/255 [00:46<10:39,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 18/255 [00:49<10:34,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 19/255 [00:51<10:30,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   8%|▊         | 20/255 [00:54<10:27,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 154
Maximum So Far : 167
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:   8%|▊         | 21/255 [00:57<10:27,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▊         | 22/255 [00:59<10:23,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▉         | 23/255 [01:02<10:20,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▉         | 24/255 [01:05<10:19,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  10%|▉         | 25/255 [01:07<10:15,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  10%|█         | 26/255 [01:10<10:11,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█         | 27/255 [01:13<10:08,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█         | 28/255 [01:15<10:10,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█▏        | 29/255 [01:18<10:05,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  12%|█▏        | 30/255 [01:21<10:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 135
Maximum So Far : 188
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  12%|█▏        | 31/255 [01:23<09:58,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 32/255 [01:26<09:59,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 33/255 [01:29<09:54,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 34/255 [01:31<09:50,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  14%|█▎        | 35/255 [01:34<09:48,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  14%|█▍        | 36/255 [01:37<09:47,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▍        | 37/255 [01:39<09:44,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▍        | 38/255 [01:42<09:41,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▌        | 39/255 [01:45<09:42,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  16%|█▌        | 40/255 [01:47<09:36,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 140
Maximum So Far : 188
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  16%|█▌        | 41/255 [01:50<09:33,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  16%|█▋        | 42/255 [01:53<09:33,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  17%|█▋        | 43/255 [01:56<09:31,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  17%|█▋        | 44/255 [01:58<09:25,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 45/255 [02:01<09:25,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 46/255 [02:04<09:20,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 47/255 [02:06<09:18,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  19%|█▉        | 48/255 [02:09<09:14,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  19%|█▉        | 49/255 [02:12<09:09,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  20%|█▉        | 50/255 [02:14<09:06,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

Generation:  20%|██        | 51/255 [02:17<09:06,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

----------------------------------------
Sample         : 50
Prompt Tokens  : 120
Maximum So Far : 188
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  20%|██        | 52/255 [02:20<09:04,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  21%|██        | 53/255 [02:22<09:00,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  21%|██        | 54/255 [02:25<08:55,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 55/255 [02:28<08:53,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 56/255 [02:30<08:49,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 57/255 [02:33<08:46,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  23%|██▎       | 58/255 [02:36<08:44,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  23%|██▎       | 59/255 [02:38<08:43,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  24%|██▎       | 60/255 [02:41<08:39,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 118
Maximum So Far : 188
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  24%|██▍       | 61/255 [02:44<08:36,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  24%|██▍       | 62/255 [02:46<08:34,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▍       | 63/255 [02:49<08:34,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▌       | 64/255 [02:52<08:31,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▌       | 65/255 [02:54<08:28,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  26%|██▌       | 66/255 [02:57<08:26,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  26%|██▋       | 67/255 [03:00<08:25,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 68/255 [03:02<08:23,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 69/255 [03:05<08:19,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 70/255 [03:08<08:16,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.56 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 157
Maximum So Far : 188
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  28%|██▊       | 71/255 [03:10<08:15,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  28%|██▊       | 72/255 [03:13<08:12,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▊       | 73/255 [03:16<08:09,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▉       | 74/255 [03:19<08:06,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▉       | 75/255 [03:21<08:03,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  30%|██▉       | 76/255 [03:24<08:03,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  30%|███       | 77/255 [03:27<07:59,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███       | 78/255 [03:29<08:03,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███       | 79/255 [03:33<08:20,  2.85s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███▏      | 80/255 [03:35<08:11,  2.81s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.56 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 172
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  32%|███▏      | 81/255 [03:38<08:02,  2.77s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  32%|███▏      | 82/255 [03:41<07:55,  2.75s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 83/255 [03:43<07:50,  2.74s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 84/255 [03:46<07:46,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 85/255 [03:49<07:41,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  34%|███▎      | 86/255 [03:51<07:38,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  34%|███▍      | 87/255 [03:54<07:36,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▍      | 88/255 [03:57<07:31,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▍      | 89/255 [04:00<07:28,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▌      | 90/255 [04:02<07:24,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 134
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  36%|███▌      | 91/255 [04:05<07:21,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  36%|███▌      | 92/255 [04:08<07:18,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  36%|███▋      | 93/255 [04:10<07:15,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  37%|███▋      | 94/255 [04:13<07:16,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  37%|███▋      | 95/255 [04:16<07:12,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 96/255 [04:18<07:08,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 97/255 [04:21<07:04,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 98/255 [04:24<07:00,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  39%|███▉      | 99/255 [04:26<06:57,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  39%|███▉      | 100/255 [04:29<06:54,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved

Generation:  40%|███▉      | 101/255 [04:32<06:52,  2.68s/it]

After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 149
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

[transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  40%|████      | 102/255 [04:34<06:49,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  40%|████      | 103/255 [04:37<06:47,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  41%|████      | 104/255 [04:40<06:44,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  41%|████      | 105/255 [04:42<06:41,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 106/255 [04:45<06:38,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 107/255 [04:48<06:36,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 108/255 [04:51<06:34,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  43%|████▎     | 109/255 [04:53<06:30,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  43%|████▎     | 110/255 [04:56<06:27,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 130
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  44%|████▎     | 111/255 [04:59<06:24,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  44%|████▍     | 112/255 [05:01<06:22,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  44%|████▍     | 113/255 [05:04<06:19,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▍     | 114/255 [05:07<06:15,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▌     | 115/255 [05:09<06:13,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▌     | 116/255 [05:12<06:10,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  46%|████▌     | 117/255 [05:15<06:08,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  46%|████▋     | 118/255 [05:17<06:06,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  47%|████▋     | 119/255 [05:20<06:04,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  47%|████▋     | 120/255 [05:23<06:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 134
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  47%|████▋     | 121/255 [05:25<05:59,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  48%|████▊     | 122/255 [05:28<05:57,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  48%|████▊     | 123/255 [05:31<05:54,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▊     | 124/255 [05:33<05:52,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▉     | 125/255 [05:36<05:50,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▉     | 126/255 [05:39<05:46,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  50%|████▉     | 127/255 [05:42<05:52,  2.75s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  50%|█████     | 128/255 [05:44<05:46,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  51%|█████     | 129/255 [05:47<05:48,  2.77s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  51%|█████     | 130/255 [05:50<05:42,  2.74s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.56 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 157
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  51%|█████▏    | 131/255 [05:53<05:38,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  52%|█████▏    | 132/255 [05:55<05:35,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  52%|█████▏    | 133/255 [05:58<05:31,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 134/255 [06:01<05:27,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 135/255 [06:03<05:24,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 136/255 [06:06<05:21,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  54%|█████▎    | 137/255 [06:09<05:17,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  54%|█████▍    | 138/255 [06:11<05:14,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  55%|█████▍    | 139/255 [06:14<05:11,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  55%|█████▍    | 140/255 [06:17<05:09,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 120
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  55%|█████▌    | 141/255 [06:19<05:06,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▌    | 142/255 [06:22<05:04,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▌    | 143/255 [06:25<05:01,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▋    | 144/255 [06:28<04:58,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  57%|█████▋    | 145/255 [06:30<04:55,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  57%|█████▋    | 146/255 [06:33<04:52,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 147/255 [06:36<04:51,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 148/255 [06:38<04:48,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 149/255 [06:41<04:45,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  59%|█████▉    | 150/255 [06:44<04:42,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved

Generation:  59%|█████▉    | 151/255 [06:46<04:40,  2.70s/it]

After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 132
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

[transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|█████▉    | 152/255 [06:49<04:37,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|██████    | 153/255 [06:52<04:34,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|██████    | 154/255 [06:54<04:31,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  61%|██████    | 155/255 [06:57<04:29,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  61%|██████    | 156/255 [07:00<04:26,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 157/255 [07:03<04:23,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 158/255 [07:05<04:21,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 159/255 [07:08<04:18,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  63%|██████▎   | 160/255 [07:11<04:15,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.56 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 155
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  63%|██████▎   | 161/255 [07:13<04:12,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▎   | 162/255 [07:16<04:10,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▍   | 163/255 [07:19<04:09,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▍   | 164/255 [07:21<04:05,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▍   | 165/255 [07:24<04:02,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▌   | 166/255 [07:27<03:59,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▌   | 167/255 [07:29<03:57,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  66%|██████▌   | 168/255 [07:32<03:53,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  66%|██████▋   | 169/255 [07:35<03:50,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  67%|██████▋   | 170/255 [07:37<03:48,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 120
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  67%|██████▋   | 171/255 [07:40<03:45,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  67%|██████▋   | 172/255 [07:43<03:42,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  68%|██████▊   | 173/255 [07:46<03:40,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  68%|██████▊   | 174/255 [07:48<03:43,  2.76s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▊   | 175/255 [07:51<03:39,  2.74s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▉   | 176/255 [07:54<03:34,  2.72s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▉   | 177/255 [07:57<03:31,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  70%|██████▉   | 178/255 [07:59<03:29,  2.73s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  70%|███████   | 179/255 [08:02<03:25,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  71%|███████   | 180/255 [08:05<03:22,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 126
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  71%|███████   | 181/255 [08:07<03:18,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  71%|███████▏  | 182/255 [08:10<03:16,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  72%|███████▏  | 183/255 [08:13<03:13,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  72%|███████▏  | 184/255 [08:15<03:10,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 185/255 [08:18<03:07,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 186/255 [08:21<03:06,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 187/255 [08:23<03:03,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  74%|███████▎  | 188/255 [08:26<03:00,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  74%|███████▍  | 189/255 [08:29<02:58,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  75%|███████▍  | 190/255 [08:32<02:55,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 119
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  75%|███████▍  | 191/255 [08:34<02:51,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  75%|███████▌  | 192/255 [08:37<02:50,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▌  | 193/255 [08:40<02:47,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▌  | 194/255 [08:42<02:44,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▋  | 195/255 [08:45<02:41,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  77%|███████▋  | 196/255 [08:48<02:38,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  77%|███████▋  | 197/255 [08:50<02:35,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 198/255 [08:53<02:32,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 199/255 [08:56<02:30,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 200/255 [08:58<02:28,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 154
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  79%|███████▉  | 201/255 [09:01<02:25,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  79%|███████▉  | 202/255 [09:04<02:22,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|███████▉  | 203/255 [09:07<02:20,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|████████  | 204/255 [09:09<02:18,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|████████  | 205/255 [09:12<02:14,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  81%|████████  | 206/255 [09:15<02:12,  2.70s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  81%|████████  | 207/255 [09:17<02:10,  2.71s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 208/255 [09:20<02:06,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 209/255 [09:23<02:03,  2.69s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 210/255 [09:25<02:00,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 116
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  83%|████████▎ | 211/255 [09:28<01:58,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  83%|████████▎ | 212/255 [09:31<01:55,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▎ | 213/255 [09:33<01:52,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▍ | 214/255 [09:36<01:49,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▍ | 215/255 [09:39<01:47,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▍ | 216/255 [09:41<01:44,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▌ | 217/255 [09:44<01:41,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▌ | 218/255 [09:47<01:39,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  86%|████████▌ | 219/255 [09:49<01:36,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  86%|████████▋ | 220/255 [09:52<01:33,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 110
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  87%|████████▋ | 221/255 [09:55<01:30,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  87%|████████▋ | 222/255 [09:57<01:28,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  87%|████████▋ | 223/255 [10:00<01:25,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  88%|████████▊ | 224/255 [10:03<01:22,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  88%|████████▊ | 225/255 [10:05<01:20,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▊ | 226/255 [10:08<01:17,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▉ | 227/255 [10:11<01:14,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▉ | 228/255 [10:13<01:12,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  90%|████████▉ | 229/255 [10:16<01:09,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  90%|█████████ | 230/255 [10:19<01:06,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 154
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  91%|█████████ | 231/255 [10:21<01:04,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  91%|█████████ | 232/255 [10:24<01:01,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  91%|█████████▏| 233/255 [10:27<00:58,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  92%|█████████▏| 234/255 [10:29<00:56,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  92%|█████████▏| 235/255 [10:32<00:53,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 236/255 [10:35<00:50,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 237/255 [10:37<00:48,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 238/255 [10:40<00:45,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  94%|█████████▎| 239/255 [10:43<00:42,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  94%|█████████▍| 240/255 [10:46<00:40,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.54 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 139
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  95%|█████████▍| 241/255 [10:48<00:37,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  95%|█████████▍| 242/255 [10:51<00:34,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  95%|█████████▌| 243/255 [10:54<00:32,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▌| 244/255 [10:56<00:29,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▌| 245/255 [10:59<00:26,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▋| 246/255 [11:02<00:23,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  97%|█████████▋| 247/255 [11:04<00:21,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  97%|█████████▋| 248/255 [11:07<00:18,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  98%|█████████▊| 249/255 [11:10<00:15,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  98%|█████████▊| 250/255 [11:12<00:13,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 11.40 GB allocated | 13.54 GB reserved
After generate  : 11.40 GB allocated | 13.56 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 159
Maximum So Far : 208
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.54 GB
----------------------------------------

Generation:  98%|█████████▊| 251/255 [11:15<00:10,  2.68s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  99%|█████████▉| 252/255 [11:18<00:08,  2.67s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  99%|█████████▉| 253/255 [11:20<00:05,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation: 100%|█████████▉| 254/255 [11:23<00:02,  2.66s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation: 100%|██████████| 255/255 [11:26<00:00,  2.69s/it]

Saved -> 51_SFT_U_C_R_Qalb_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 5.89 GB
Reserved  : 11.08 GB
Max Allocated : 13.13 GB
Max Reserved  : 13.72 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C_R_PD
INPUT COLUMNS: ['User Utterance', 'Context', 'User Role', 'Model Role', 'Power Distance']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 5.89 GB
Reserved  : 11.08 GB
Max Allocated : 5.89 GB
Max Reserved  : 11.08 GB
==========================================


Loading FRESH Qalb model...
Model: enstazao/Qalb-1.0-8B-Instruct

Loading weights: 100%|██████████| 291/291 [00:04<00:00, 63.64it/s]

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

================ MEMORY AFTER MODEL LOAD ================
Allocated : 13.32 GB
Reserved  : 15.39 GB
Max Allocated : 14.14 GB
Max Reserved  : 15.39 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 51/51 [00:00<00:00, 1728.25it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 51
Maximum total tokens : 311
Maximum response tokens : 88
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 13.32 GB
Reserved  : 15.39 GB
Max Allocated : 14.14 GB
Max Reserved  : 15.39 GB
==========================================



================================================
TRAINING U_C_R_PD
================================================

================================================
TRAINING COMPLETE
Training time: 7.60 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 13.35 GB
Reserved  : 15.68 GB
Max Allocated : 15.10 GB
Max Reserved  : 15.68 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context', 'User Role', 'Model Role', 'Power Distance']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.68 GB reserved
After generate  : 13.35 GB allocated | 15.68 GB reserved

Generation:   0%|          | 1/255 [00:03<13:42,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

----------------------------------------
Sample         : 0
Prompt Tokens  : 143
Maximum So Far : 143
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:   1%|          | 2/255 [00:06<13:40,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   1%|          | 3/255 [00:09<13:33,  3.23s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 4/255 [00:12<13:29,  3.22s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 5/255 [00:16<13:32,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   2%|▏         | 6/255 [00:19<13:25,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   3%|▎         | 7/255 [00:22<13:20,  3.23s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   3%|▎         | 8/255 [00:25<13:22,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   4%|▎         | 9/255 [00:29<13:18,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   4%|▍         | 10/255 [00:32<13:17,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 147
Maximum So Far : 172
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:   4%|▍         | 11/255 [00:35<13:16,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▍         | 12/255 [00:38<13:09,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▌         | 13/255 [00:42<13:09,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   5%|▌         | 14/255 [00:45<13:05,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   6%|▌         | 15/255 [00:48<13:06,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   6%|▋         | 16/255 [00:52<12:59,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 17/255 [00:55<12:55,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 18/255 [00:58<12:52,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   7%|▋         | 19/255 [01:01<12:46,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   8%|▊         | 20/255 [01:05<12:51,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 160
Maximum So Far : 173
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:   8%|▊         | 21/255 [01:08<12:44,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▊         | 22/255 [01:11<12:40,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▉         | 23/255 [01:14<12:42,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:   9%|▉         | 24/255 [01:18<12:35,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  10%|▉         | 25/255 [01:21<12:35,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  10%|█         | 26/255 [01:24<12:29,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█         | 27/255 [01:28<12:24,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█         | 28/255 [01:31<12:17,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  11%|█▏        | 29/255 [01:34<12:14,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  12%|█▏        | 30/255 [01:37<12:09,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved

Generation:  12%|█▏        | 31/255 [01:40<12:04,  3.23s/it]

After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 141
Maximum So Far : 194
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

[transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 32/255 [01:44<12:01,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 33/255 [01:47<11:57,  3.23s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  13%|█▎        | 34/255 [01:50<11:54,  3.23s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  14%|█▎        | 35/255 [01:53<11:51,  3.23s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  14%|█▍        | 36/255 [01:57<11:50,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▍        | 37/255 [02:00<11:47,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▍        | 38/255 [02:03<11:43,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  15%|█▌        | 39/255 [02:06<11:42,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  16%|█▌        | 40/255 [02:10<11:38,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 146
Maximum So Far : 194
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  16%|█▌        | 41/255 [02:13<11:34,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  16%|█▋        | 42/255 [02:16<11:32,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  17%|█▋        | 43/255 [02:19<11:27,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  17%|█▋        | 44/255 [02:23<11:23,  3.24s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 45/255 [02:26<11:22,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 46/255 [02:29<11:19,  3.25s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  18%|█▊        | 47/255 [02:32<11:18,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  19%|█▉        | 48/255 [02:36<11:16,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  19%|█▉        | 49/255 [02:39<11:10,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  20%|█▉        | 50/255 [02:42<11:09,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 126
Maximum So Far : 194
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  20%|██        | 51/255 [02:46<11:09,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  20%|██        | 52/255 [02:49<11:06,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  21%|██        | 53/255 [02:52<11:01,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  21%|██        | 54/255 [02:55<11:00,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 55/255 [02:59<10:57,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 56/255 [03:02<10:53,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  22%|██▏       | 57/255 [03:05<10:52,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  23%|██▎       | 58/255 [03:09<10:48,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  23%|██▎       | 59/255 [03:12<10:43,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  24%|██▎       | 60/255 [03:15<10:39,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 124
Maximum So Far : 194
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  24%|██▍       | 61/255 [03:18<10:36,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  24%|██▍       | 62/255 [03:22<10:33,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▍       | 63/255 [03:25<10:30,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▌       | 64/255 [03:28<10:29,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  25%|██▌       | 65/255 [03:31<10:21,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  26%|██▌       | 66/255 [03:35<10:18,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  26%|██▋       | 67/255 [03:38<10:16,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 68/255 [03:41<10:11,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 69/255 [03:45<10:11,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  27%|██▋       | 70/255 [03:48<10:05,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 163
Maximum So Far : 194
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  28%|██▊       | 71/255 [03:51<10:00,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  28%|██▊       | 72/255 [03:54<10:04,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▊       | 73/255 [03:58<09:59,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▉       | 74/255 [04:01<09:55,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  29%|██▉       | 75/255 [04:04<09:52,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  30%|██▉       | 76/255 [04:08<09:49,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  30%|███       | 77/255 [04:11<09:46,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███       | 78/255 [04:14<09:44,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███       | 79/255 [04:18<09:42,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  31%|███▏      | 80/255 [04:21<09:36,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 178
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  32%|███▏      | 81/255 [04:24<09:35,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  32%|███▏      | 82/255 [04:27<09:29,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 83/255 [04:31<09:22,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 84/255 [04:34<09:20,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  33%|███▎      | 85/255 [04:37<09:17,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  34%|███▎      | 86/255 [04:40<09:12,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  34%|███▍      | 87/255 [04:44<09:08,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▍      | 88/255 [04:47<09:07,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▍      | 89/255 [04:50<09:05,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  35%|███▌      | 90/255 [04:54<08:59,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 140
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  36%|███▌      | 91/255 [04:57<08:57,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  36%|███▌      | 92/255 [05:00<08:52,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  36%|███▋      | 93/255 [05:03<08:49,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  37%|███▋      | 94/255 [05:07<08:46,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  37%|███▋      | 95/255 [05:10<08:42,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 96/255 [05:13<08:42,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 97/255 [05:17<08:38,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  38%|███▊      | 98/255 [05:20<08:38,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  39%|███▉      | 99/255 [05:23<08:32,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  39%|███▉      | 100/255 [05:26<08:29,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 155
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  40%|███▉      | 101/255 [05:30<08:27,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  40%|████      | 102/255 [05:33<08:22,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  40%|████      | 103/255 [05:36<08:19,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  41%|████      | 104/255 [05:40<08:14,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  41%|████      | 105/255 [05:43<08:10,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 106/255 [05:46<08:11,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 107/255 [05:49<08:06,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  42%|████▏     | 108/255 [05:53<08:03,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  43%|████▎     | 109/255 [05:56<08:00,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  43%|████▎     | 110/255 [05:59<07:55,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 136
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  44%|████▎     | 111/255 [06:03<07:53,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  44%|████▍     | 112/255 [06:06<07:49,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  44%|████▍     | 113/255 [06:09<07:47,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▍     | 114/255 [06:12<07:43,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▌     | 115/255 [06:16<07:42,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  45%|████▌     | 116/255 [06:19<07:35,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  46%|████▌     | 117/255 [06:22<07:31,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  46%|████▋     | 118/255 [06:26<07:31,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  47%|████▋     | 119/255 [06:29<07:25,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  47%|████▋     | 120/255 [06:32<07:23,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 140
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  47%|████▋     | 121/255 [06:35<07:19,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  48%|████▊     | 122/255 [06:39<07:15,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  48%|████▊     | 123/255 [06:42<07:12,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▊     | 124/255 [06:45<07:09,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▉     | 125/255 [06:49<07:08,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  49%|████▉     | 126/255 [06:52<07:02,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  50%|████▉     | 127/255 [06:55<06:59,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  50%|█████     | 128/255 [06:58<06:55,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  51%|█████     | 129/255 [07:02<06:53,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  51%|█████     | 130/255 [07:05<06:53,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 163
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  51%|█████▏    | 131/255 [07:08<06:48,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  52%|█████▏    | 132/255 [07:11<06:43,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  52%|█████▏    | 133/255 [07:15<06:40,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 134/255 [07:18<06:35,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 135/255 [07:21<06:32,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  53%|█████▎    | 136/255 [07:25<06:30,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  54%|█████▎    | 137/255 [07:28<06:28,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  54%|█████▍    | 138/255 [07:31<06:23,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  55%|█████▍    | 139/255 [07:34<06:19,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  55%|█████▍    | 140/255 [07:38<06:17,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 126
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  55%|█████▌    | 141/255 [07:41<06:14,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▌    | 142/255 [07:44<06:12,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▌    | 143/255 [07:48<06:09,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  56%|█████▋    | 144/255 [07:51<06:03,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  57%|█████▋    | 145/255 [07:54<06:02,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  57%|█████▋    | 146/255 [07:57<05:57,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 147/255 [08:01<05:54,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 148/255 [08:04<05:50,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  58%|█████▊    | 149/255 [08:07<05:46,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  59%|█████▉    | 150/255 [08:11<05:44,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 138
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  59%|█████▉    | 151/255 [08:14<05:39,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|█████▉    | 152/255 [08:17<05:39,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|██████    | 153/255 [08:20<05:34,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  60%|██████    | 154/255 [08:24<05:33,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  61%|██████    | 155/255 [08:27<05:29,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  61%|██████    | 156/255 [08:30<05:24,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 157/255 [08:34<05:22,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 158/255 [08:37<05:18,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  62%|██████▏   | 159/255 [08:40<05:14,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  63%|██████▎   | 160/255 [08:43<05:10,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 161
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  63%|██████▎   | 161/255 [08:47<05:07,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▎   | 162/255 [08:50<05:06,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▍   | 163/255 [08:53<05:02,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  64%|██████▍   | 164/255 [08:57<05:00,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▍   | 165/255 [09:00<04:55,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▌   | 166/255 [09:03<04:51,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  65%|██████▌   | 167/255 [09:06<04:50,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  66%|██████▌   | 168/255 [09:10<04:46,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  66%|██████▋   | 169/255 [09:13<04:45,  3.32s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  67%|██████▋   | 170/255 [09:16<04:42,  3.32s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 126
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  67%|██████▋   | 171/255 [09:20<04:37,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  67%|██████▋   | 172/255 [09:23<04:33,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  68%|██████▊   | 173/255 [09:26<04:29,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  68%|██████▊   | 174/255 [09:30<04:25,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▊   | 175/255 [09:33<04:21,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▉   | 176/255 [09:36<04:19,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  69%|██████▉   | 177/255 [09:39<04:14,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  70%|██████▉   | 178/255 [09:43<04:10,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  70%|███████   | 179/255 [09:46<04:10,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  71%|███████   | 180/255 [09:49<04:06,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 132
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  71%|███████   | 181/255 [09:53<04:03,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  71%|███████▏  | 182/255 [09:56<04:00,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  72%|███████▏  | 183/255 [09:59<03:55,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  72%|███████▏  | 184/255 [10:02<03:53,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 185/255 [10:06<03:49,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 186/255 [10:09<03:46,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  73%|███████▎  | 187/255 [10:12<03:42,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  74%|███████▎  | 188/255 [10:15<03:39,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  74%|███████▍  | 189/255 [10:19<03:36,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  75%|███████▍  | 190/255 [10:22<03:31,  3.26s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 125
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  75%|███████▍  | 191/255 [10:25<03:30,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  75%|███████▌  | 192/255 [10:29<03:26,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▌  | 193/255 [10:32<03:22,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▌  | 194/255 [10:35<03:20,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  76%|███████▋  | 195/255 [10:38<03:16,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  77%|███████▋  | 196/255 [10:42<03:14,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  77%|███████▋  | 197/255 [10:45<03:10,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 198/255 [10:48<03:07,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 199/255 [10:52<03:03,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  78%|███████▊  | 200/255 [10:55<03:00,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 160
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  79%|███████▉  | 201/255 [10:58<02:57,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  79%|███████▉  | 202/255 [11:01<02:54,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|███████▉  | 203/255 [11:05<02:51,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|████████  | 204/255 [11:08<02:47,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  80%|████████  | 205/255 [11:11<02:44,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  81%|████████  | 206/255 [11:15<02:41,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  81%|████████  | 207/255 [11:18<02:37,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 208/255 [11:21<02:34,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 209/255 [11:24<02:31,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  82%|████████▏ | 210/255 [11:28<02:28,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 122
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  83%|████████▎ | 211/255 [11:31<02:24,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  83%|████████▎ | 212/255 [11:34<02:21,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▎ | 213/255 [11:38<02:18,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▍ | 214/255 [11:41<02:14,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  84%|████████▍ | 215/255 [11:44<02:11,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▍ | 216/255 [11:47<02:07,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▌ | 217/255 [11:51<02:04,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  85%|████████▌ | 218/255 [11:54<02:01,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  86%|████████▌ | 219/255 [11:57<01:58,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  86%|████████▋ | 220/255 [12:01<01:54,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 116
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  87%|████████▋ | 221/255 [12:04<01:51,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  87%|████████▋ | 222/255 [12:07<01:48,  3.28s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  87%|████████▋ | 223/255 [12:10<01:44,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  88%|████████▊ | 224/255 [12:14<01:41,  3.27s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  88%|████████▊ | 225/255 [12:17<01:39,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▊ | 226/255 [12:20<01:35,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▉ | 227/255 [12:24<01:32,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  89%|████████▉ | 228/255 [12:27<01:29,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  90%|████████▉ | 229/255 [12:30<01:25,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  90%|█████████ | 230/255 [12:34<01:22,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 160
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  91%|█████████ | 231/255 [12:37<01:19,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  91%|█████████ | 232/255 [12:40<01:16,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  91%|█████████▏| 233/255 [12:43<01:12,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  92%|█████████▏| 234/255 [12:47<01:09,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  92%|█████████▏| 235/255 [12:50<01:06,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 236/255 [12:53<01:02,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 237/255 [12:57<00:59,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  93%|█████████▎| 238/255 [13:00<00:56,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  94%|█████████▎| 239/255 [13:03<00:52,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  94%|█████████▍| 240/255 [13:07<00:49,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.50 GB reserved

Generation:  95%|█████████▍| 241/255 [13:10<00:46,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

----------------------------------------
Sample         : 240
Prompt Tokens  : 145
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  95%|█████████▍| 242/255 [13:13<00:43,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  95%|█████████▌| 243/255 [13:16<00:39,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▌| 244/255 [13:20<00:36,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▌| 245/255 [13:23<00:32,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  96%|█████████▋| 246/255 [13:26<00:29,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  97%|█████████▋| 247/255 [13:30<00:26,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  97%|█████████▋| 248/255 [13:33<00:23,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  98%|█████████▊| 249/255 [13:36<00:19,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  98%|█████████▊| 250/255 [13:40<00:16,  3.30s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Before generate : 13.35 GB allocated | 15.50 GB reserved
After generate  : 13.35 GB allocated | 15.52 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 165
Maximum So Far : 214
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.50 GB
----------------------------------------

Generation:  98%|█████████▊| 251/255 [13:43<00:13,  3.29s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  99%|█████████▉| 252/255 [13:46<00:09,  3.32s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation:  99%|█████████▉| 253/255 [13:49<00:06,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation: 100%|█████████▉| 254/255 [13:53<00:03,  3.31s/it][transformers] Both `max_new_tokens` (=40) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Generation: 100%|██████████| 255/255 [13:56<00:00,  3.28s/it]

Saved -> 51_SFT_U_C_R_PD_Qalb_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 7.84 GB
Reserved  : 13.04 GB
Max Allocated : 15.10 GB
Max Reserved  : 15.68 GB
==========================================




===========================================================================
ALL FOUR QALB SFT EXPERIMENTS COMPLETED
===========================================================================

Generated files:
1. 51_SFT_U_Qalb_test.csv
2. 51_SFT_U_C_Qalb_test.csv
3. 51_SFT_U_C_R_Qalb_test.csv
4. 51_SFT_U_C_R_PD_Qalb_test.csv
===========================================================================