In [1]:
import os
import gc
import time
import warnings

import torch
import pandas as pd

from tqdm.auto import tqdm

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)

warnings.filterwarnings("ignore")


# ============================================================
# CONFIGURATION
# ============================================================

DATA_PATH = r"P_CULTA_V2_306.csv"

# 70/30 train-test split of the complete 306-item dataset
TRAIN_RATIO = 0.70
RANDOM_SEED = 42

MODEL_ID = "Qwen/Qwen2.5-7B-Instruct"

NUM_EPOCHS = 10

# Same general token setup as your previous generation code
MAX_LENGTH = 2048
MAX_NEW_TOKENS = 40


# ============================================================
# QLoRA CONFIGURATION
# ============================================================

LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05


# ============================================================
# TRAINING CONFIGURATION
# ============================================================

BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 8

LEARNING_RATE = 2e-4


# ============================================================
# LOAD DATA
# ============================================================

full_df = pd.read_csv(DATA_PATH).reset_index(drop=True)

# Reproducible 70/30 split
train_df = full_df.sample(frac=TRAIN_RATIO, random_state=RANDOM_SEED)
test_df = full_df.drop(train_df.index)

# Reset indices because later generation code uses the dataframe index
train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print("==============================================")
print("DATASET")
print("==============================================")

print(f"Full shape  : {full_df.shape}")
print(f"Train shape : {train_df.shape}")
print(f"Test shape  : {test_df.shape}")

print("\nColumns:")
print(train_df.columns.tolist())

print("\n==============================================\n")


# ============================================================
# CHECK REQUIRED COLUMNS
# ============================================================

required_columns = [
    "User Utterance",
    "Context",
    "User Role",
    "Model Role",
    "Power Distance",
    "Gold Response",
]

for col in required_columns:

    if col not in train_df.columns:

        raise ValueError(
            f"Missing column in training file: {col}"
        )

    if col != "Gold Response" and col not in test_df.columns:

        raise ValueError(
            f"Missing column in test file: {col}"
        )


# ============================================================
# GPU CHECK
# ============================================================

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU not available."
    )


print("\n================ GPU INFO ================")

print(
    f"GPU : {torch.cuda.get_device_name(0)}"
)

props = torch.cuda.get_device_properties(0)

print(
    f"Total VRAM : "
    f"{props.total_memory / 1024**3:.2f} GB"
)

print(
    f"Allocated : "
    f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB"
)

print(
    f"Reserved  : "
    f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB"
)

print("==========================================\n")


# ============================================================
# SYSTEM INSTRUCTION
# ============================================================
#
# This is intentionally the SAME instruction used
# during your prompting experiments.
#
# There are NO demonstrations here.
#
# ============================================================

SYSTEM_INSTRUCTION = (
    "Generate a natural Urdu response. "
    "Output only the response utterance. "
    "Do not explain. "
    "Do not narrate. "
    "Do not add extra context. "
    "Do not ask unnecessary follow-up questions."
)


# ============================================================
# 4-BIT QUANTIZATION
# ============================================================

bnb_config = BitsAndBytesConfig(

    load_in_4bit=True,

    bnb_4bit_use_double_quant=True,

    bnb_4bit_quant_type="nf4",

    bnb_4bit_compute_dtype=torch.float16,
)


# ============================================================
# MEMORY PRINT FUNCTION
# ============================================================

def print_memory(title):

    print(
        f"\n================ {title} ================"
    )

    print(
        f"Allocated : "
        f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB"
    )

    print(
        f"Reserved  : "
        f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB"
    )

    print(
        f"Max Allocated : "
        f"{torch.cuda.max_memory_allocated() / 1024**3:.2f} GB"
    )

    print(
        f"Max Reserved  : "
        f"{torch.cuda.max_memory_reserved() / 1024**3:.2f} GB"
    )

    print("==========================================\n")


# ============================================================
# GPU CLEANUP
# ============================================================

def cleanup_gpu():

    gc.collect()

    if torch.cuda.is_available():

        torch.cuda.empty_cache()

        try:

            torch.cuda.ipc_collect()

        except Exception:

            pass


# ============================================================
# LOAD FRESH MODEL
# ============================================================
#
# IMPORTANT:
# A completely fresh model is loaded for every
# experiment.
#
# trust_remote_code=False prevents Transformers from
# trying to download custom_generate/generate.py.
#
# ============================================================

def load_fresh_model():

    print("\nLoading FRESH model...")

    # --------------------------------------------------------
    # MODEL
    # --------------------------------------------------------

    model = AutoModelForCausalLM.from_pretrained(

        MODEL_ID,

        quantization_config=bnb_config,

        device_map="auto",

        # IMPORTANT FIX
        trust_remote_code=False,
    )

    # --------------------------------------------------------
    # TOKENIZER
    # --------------------------------------------------------

    tokenizer = AutoTokenizer.from_pretrained(

        MODEL_ID,

        # IMPORTANT FIX
        trust_remote_code=False,
    )

    # --------------------------------------------------------
    # PAD TOKEN
    # --------------------------------------------------------

    if tokenizer.pad_token is None:

        tokenizer.pad_token = tokenizer.eos_token

    model.config.pad_token_id = tokenizer.pad_token_id

    # --------------------------------------------------------
    # PREPARE 4-BIT MODEL FOR TRAINING
    # --------------------------------------------------------

    model = prepare_model_for_kbit_training(
        model
    )

    # --------------------------------------------------------
    # LoRA
    # --------------------------------------------------------

    lora_config = LoraConfig(

        r=LORA_R,

        lora_alpha=LORA_ALPHA,

        lora_dropout=LORA_DROPOUT,

        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],

        bias="none",

        task_type="CAUSAL_LM",
    )

    model = get_peft_model(

        model,

        lora_config,
    )

    # --------------------------------------------------------
    # TRAINABLE PARAMETERS
    # --------------------------------------------------------

    model.print_trainable_parameters()

    print_memory(
        "MEMORY AFTER MODEL LOAD"
    )

    return model, tokenizer


# ============================================================
# BUILD USER CONTENT
# ============================================================

def build_user_content(
    row,
    input_columns,
):

    parts = []

    for col in input_columns:

        value = row[col]

        if pd.isna(value):

            value = ""

        value = str(value).strip()

        parts.append(
            f'{col}: "{value}"'
        )

    return "\n\n".join(parts)


# ============================================================
# PREPARE SFT DATA
# ============================================================
#
# TRAINING FORMAT:
#
# SYSTEM
# USER
# ASSISTANT = GOLD RESPONSE
#
# Loss is calculated ONLY on the response.
#
# ============================================================

def prepare_training_dataset(
    df,
    input_columns,
    tokenizer,
):

    dataset = []

    max_total_tokens = 0

    max_response_tokens = 0

    print(
        "\nBuilding training examples..."
    )

    for _, row in tqdm(

        df.iterrows(),

        total=len(df),

        desc="Preparing SFT data",

    ):

        # ----------------------------------------------------
        # USER INPUT
        # ----------------------------------------------------

        user_content = build_user_content(

            row,

            input_columns,
        )

        # ----------------------------------------------------
        # GOLD RESPONSE
        # ----------------------------------------------------

        gold_response = row[
            "Gold Response"
        ]

        if pd.isna(gold_response):

            gold_response = ""

        gold_response = str(
            gold_response
        ).strip()

        # ----------------------------------------------------
        # PROMPT ONLY
        # ----------------------------------------------------

        prompt_messages = [

            {
                "role": "system",
                "content": SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",
                "content": user_content,
            },
        ]

        prompt_text = tokenizer.apply_chat_template(

            prompt_messages,

            tokenize=False,

            add_generation_prompt=True,
        )

        # ----------------------------------------------------
        # FULL TRAINING EXAMPLE
        # ----------------------------------------------------

        full_messages = [

            {
                "role": "system",
                "content": SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",
                "content": user_content,
            },

            {
                "role": "assistant",
                "content": gold_response,
            },
        ]

        full_text = tokenizer.apply_chat_template(

            full_messages,

            tokenize=False,

            add_generation_prompt=False,
        )

        # ----------------------------------------------------
        # TOKENIZE PROMPT
        # ----------------------------------------------------

        prompt_tokens = tokenizer(

            prompt_text,

            add_special_tokens=False,

        )["input_ids"]

        prompt_length = len(
            prompt_tokens
        )

        # ----------------------------------------------------
        # TOKENIZE FULL SEQUENCE
        # ----------------------------------------------------

        full_tokens = tokenizer(

            full_text,

            add_special_tokens=False,

            truncation=True,

            max_length=MAX_LENGTH,
        )

        input_ids = full_tokens[
            "input_ids"
        ]

        attention_mask = full_tokens[
            "attention_mask"
        ]

        # ----------------------------------------------------
        # LABELS
        #
        # Prompt tokens = -100
        #
        # Gold response tokens = actual token IDs
        #
        # Therefore loss is only calculated on response.
        # ----------------------------------------------------

        labels = []

        for token_index in range(
            len(input_ids)
        ):

            if token_index < prompt_length:

                labels.append(-100)

            else:

                labels.append(
                    input_ids[token_index]
                )

        # ----------------------------------------------------
        # STATISTICS
        # ----------------------------------------------------

        response_length = max(

            0,

            len(input_ids) - prompt_length
        )

        max_total_tokens = max(

            max_total_tokens,

            len(input_ids)
        )

        max_response_tokens = max(

            max_response_tokens,

            response_length
        )

        # ----------------------------------------------------
        # ADD EXAMPLE
        # ----------------------------------------------------

        dataset.append({

            "input_ids": input_ids,

            "attention_mask": attention_mask,

            "labels": labels,

        })

    # --------------------------------------------------------
    # PRINT STATISTICS
    # --------------------------------------------------------

    print(
        f"\nTraining examples : "
        f"{len(dataset)}"
    )

    print(
        f"Maximum total tokens : "
        f"{max_total_tokens}"
    )

    print(
        f"Maximum response tokens : "
        f"{max_response_tokens}"
    )

    print(
        f"MAX_LENGTH : "
        f"{MAX_LENGTH}"
    )

    return dataset


# ============================================================
# PYTORCH DATASET
# ============================================================

class SFTDataset(
    torch.utils.data.Dataset
):

    def __init__(
        self,
        data,
    ):

        self.data = data

    def __len__(self):

        return len(self.data)

    def __getitem__(
        self,
        idx,
    ):

        return self.data[idx]


# ============================================================
# GENERATE TEST RESPONSES
# ============================================================

def generate_test_responses(

    model,

    tokenizer,

    test_df,

    input_columns,

    output_path,

):

    model.eval()

    responses = []

    max_tokens_seen = 0

    print(
        "\n================================================"
    )

    print(
        "GENERATING TEST RESPONSES"
    )

    print(
        f"Input columns: {input_columns}"
    )

    print(
        f"Test samples: {len(test_df)}"
    )

    print(
        "================================================\n"
    )

    for i, row in tqdm(

        test_df.iterrows(),

        total=len(test_df),

        desc="Generation",

    ):

        # ----------------------------------------------------
        # BUILD INPUT
        # ----------------------------------------------------

        user_content = build_user_content(

            row,

            input_columns,
        )

        # ----------------------------------------------------
        # TEST PROMPT
        # ----------------------------------------------------

        messages = [

            {
                "role": "system",

                "content":
                    SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",

                "content":
                    user_content,
            },
        ]

        # ----------------------------------------------------
        # CHAT TEMPLATE
        # ----------------------------------------------------

        text_in = tokenizer.apply_chat_template(

            messages,

            tokenize=False,

            add_generation_prompt=True,
        )

        # ----------------------------------------------------
        # TOKEN COUNT
        # ----------------------------------------------------

        num_tokens = len(

            tokenizer(
                text_in
            )["input_ids"]
        )

        max_tokens_seen = max(

            max_tokens_seen,

            num_tokens,
        )

        # ----------------------------------------------------
        # TOKENIZE
        # ----------------------------------------------------

        inputs = tokenizer(

            text_in,

            return_tensors="pt",

            truncation=True,

            max_length=MAX_LENGTH,
        )

        # Move inputs to model's device
        inputs = {
            key: value.to(model.device)
            for key, value in inputs.items()
        }

        # ----------------------------------------------------
        # GENERATION
        # ----------------------------------------------------

        with torch.no_grad():

            if i % 10 == 0:

                print(

                    f"\nBefore generate : "

                    f"{torch.cuda.memory_allocated()/1024**3:.2f} GB allocated | "

                    f"{torch.cuda.memory_reserved()/1024**3:.2f} GB reserved"
                )

            outputs = model.generate(

                **inputs,

                max_new_tokens=MAX_NEW_TOKENS,

                temperature=0.3,

                do_sample=True,

                repetition_penalty=1.1,

                pad_token_id=
                    tokenizer.eos_token_id,

                use_cache=True,
            )

            if i % 10 == 0:

                print(

                    f"After generate  : "

                    f"{torch.cuda.memory_allocated()/1024**3:.2f} GB allocated | "

                    f"{torch.cuda.memory_reserved()/1024**3:.2f} GB reserved"
                )

        # ----------------------------------------------------
        # REMOVE INPUT TOKENS
        # ----------------------------------------------------

        new_tokens = outputs[

            0

        ][

            inputs["input_ids"].shape[1]:
        ]

        # ----------------------------------------------------
        # DECODE RESPONSE
        # ----------------------------------------------------

        response = tokenizer.decode(

            new_tokens,

            skip_special_tokens=True,
        ).strip()

        responses.append(
            response
        )

        # ----------------------------------------------------
        # FREE MEMORY
        # ----------------------------------------------------

        del outputs

        del new_tokens

        del inputs

        gc.collect()

        torch.cuda.empty_cache()

        # ----------------------------------------------------
        # DIAGNOSTICS
        # ----------------------------------------------------

        if i % 10 == 0:

            print(
                "\n----------------------------------------"
            )

            print(
                f"Sample         : {i}"
            )

            print(
                f"Prompt Tokens  : {num_tokens}"
            )

            print(
                f"Maximum So Far : {max_tokens_seen}"
            )

            print(
                f"Allocated VRAM : "
                f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
            )

            print(
                f"Reserved VRAM  : "
                f"{torch.cuda.memory_reserved()/1024**3:.2f} GB"
            )

            print(
                "----------------------------------------"
            )

        # ----------------------------------------------------
        # BACKUP EVERY 25 SAMPLES
        # ----------------------------------------------------

        if i % 25 == 0 and i > 0:

            backup = test_df.copy()

            backup[
                "Qwen_Response"
            ] = (

                responses
                + [""] * (

                    len(test_df)
                    - len(responses)
                )
            )

            backup.to_csv(

                output_path.replace(

                    ".csv",

                    "_backup.csv",
                ),

                index=False,

                encoding="utf-8-sig",
            )

    # ========================================================
    # FINAL SAVE
    # ========================================================

    result = test_df.copy()

    result[
        "Qwen_Response"
    ] = responses

    result.to_csv(

        output_path,

        index=False,

        encoding="utf-8-sig",
    )

    print(
        f"\nSaved -> {output_path}"
    )

    return result


# ============================================================
# RUN ONE COMPLETE SFT EXPERIMENT
# ============================================================

def run_sft_experiment(

    experiment_name,

    input_columns,

    output_path,
):

    print("\n\n")

    print("=" * 75)

    print(
        f"STARTING SFT EXPERIMENT: "
        f"{experiment_name}"
    )

    print(
        f"INPUT COLUMNS: "
        f"{input_columns}"
    )

    print(
        f"EPOCHS: "
        f"{NUM_EPOCHS}"
    )

    print("=" * 75)

    # --------------------------------------------------------
    # CLEAN GPU
    # --------------------------------------------------------

    cleanup_gpu()

    torch.cuda.reset_peak_memory_stats()

    print_memory(
        "MEMORY BEFORE MODEL LOAD"
    )

    # --------------------------------------------------------
    # FRESH MODEL
    # --------------------------------------------------------

    model, tokenizer = (
        load_fresh_model()
    )

    # --------------------------------------------------------
    # PREPARE TRAIN DATA
    # --------------------------------------------------------

    train_data = (
        prepare_training_dataset(

            train_df,

            input_columns,

            tokenizer,
        )
    )

    train_dataset = SFTDataset(
        train_data
    )

    # --------------------------------------------------------
    # DATA COLLATOR
    # --------------------------------------------------------

    data_collator = DataCollatorForSeq2Seq(

        tokenizer=tokenizer,

        padding=True,

        return_tensors="pt",
    )

    print_memory(
        "MEMORY BEFORE TRAINING"
    )

    # --------------------------------------------------------
    # TRAINING ARGUMENTS
    # --------------------------------------------------------

    training_args = TrainingArguments(

        output_dir=(
            f"./sft_{experiment_name}"
        ),

        num_train_epochs=NUM_EPOCHS,

        per_device_train_batch_size=
            BATCH_SIZE,

        gradient_accumulation_steps=
            GRADIENT_ACCUMULATION,

        learning_rate=
            LEARNING_RATE,

        fp16=True,

        optim="paged_adamw_8bit",

        logging_steps=1,

        save_strategy="no",

        report_to="none",

        remove_unused_columns=False,

        gradient_checkpointing=True,

        max_grad_norm=0.3,

        warmup_ratio=0.03,

        lr_scheduler_type="cosine",
    )

    # --------------------------------------------------------
    # TRAINER
    # --------------------------------------------------------

    trainer = Trainer(

        model=model,

        args=training_args,

        train_dataset=train_dataset,

        data_collator=data_collator,
    )

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    print("\n")

    print(
        "================================================"
    )

    print(
        f"TRAINING {experiment_name}"
    )

    print(
        "================================================"
    )

    start_time = time.time()

    trainer.train()

    training_time = (
        time.time()
        - start_time
    )

    print(
        "\n================================================"
    )

    print(
        "TRAINING COMPLETE"
    )

    print(
        f"Training time: "
        f"{training_time / 60:.2f} minutes"
    )

    print(
        "================================================"
    )

    print_memory(
        "MEMORY AFTER TRAINING"
    )

    # --------------------------------------------------------
    # GENERATE TEST
    # --------------------------------------------------------

    result = generate_test_responses(

        model=model,

        tokenizer=tokenizer,

        test_df=test_df,

        input_columns=input_columns,

        output_path=output_path,
    )

    # --------------------------------------------------------
    # CLEANUP
    # --------------------------------------------------------

    print(
        "\nCleaning up model..."
    )

    del trainer

    del model

    del tokenizer

    del train_dataset

    del train_data

    cleanup_gpu()

    print_memory(
        "FINAL MEMORY AFTER CLEANUP"
    )

    return result


# ============================================================
# EXPERIMENT 1
# U
# ============================================================

result_U = run_sft_experiment(

    experiment_name="U",

    input_columns=[
        "User Utterance"
    ],

    output_path=(
        r"SFT_U_qwen_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 2
# U + CONTEXT
# ============================================================

result_UC = run_sft_experiment(

    experiment_name="U_C",

    input_columns=[
        "User Utterance",
        "Context",
    ],

    output_path=(
        r"SFT_U_C_qwen_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 3
# U + CONTEXT + ROLES
# ============================================================

result_UCR = run_sft_experiment(

    experiment_name="U_C_R",

    input_columns=[
        "User Utterance",
        "Context",
        "User Role",
        "Model Role",
    ],

    output_path=(
        r"SFT_U_C_R_qwen_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 4
# U + CONTEXT + ROLES + POWER DISTANCE
# ============================================================

result_UCRPD = run_sft_experiment(

    experiment_name="U_C_R_PD",

    input_columns=[
        "User Utterance",
        "Context",
        "User Role",
        "Model Role",
        "Power Distance",
    ],

    output_path=(
        r"SFT_U_C_R_PD_qwen_test.csv"
    ),
)


# ============================================================
# DONE
# ============================================================

print("\n\n")

print("=" * 75)

print(
    "ALL FOUR SFT EXPERIMENTS COMPLETED"
)

print("=" * 75)

print(
    "\nGenerated files:"
)

print(
    r"1. SFT_U_qwen_test.csv"
)

print(
    r"2. SFT_U_C_qwen_test.csv"
)

print(
    r"3. SFT_U_C_R_qwen_test.csv"
)

print(
    r"4. SFT_U_C_R_PD_qwen_test.csv"
)

print("=" * 75)

D:\stdFurqan\FYP_AA\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

==============================================
DATASET
==============================================
Full shape  : (306, 11)
Train shape : (214, 11)
Test shape  : (92, 11)

Columns:
['Language', 'Topic', 'User Role', 'Model Role', 'Power Distance', 'Register', 'Pragmatic Genre', 'Sensitivity', 'User Utterance', 'Context', 'Gold Response']

==============================================


================ GPU INFO ================
GPU : NVIDIA GeForce RTX 4080 SUPER
Total VRAM : 15.99 GB
Allocated : 0.00 GB
Reserved  : 0.00 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U
INPUT COLUMNS: ['User Utterance']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 0.00 GB
Reserved  : 0.00 GB
Max Allocated : 0.00 GB
Max Reserved  : 0.00 GB
==========================================


Loading FRESH model...

Loading weights: 100%|██████████| 339/339 [00:04<00:00, 78.73it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

================ MEMORY AFTER MODEL LOAD ================
Allocated : 7.36 GB
Reserved  : 9.45 GB
Max Allocated : 8.23 GB
Max Reserved  : 9.45 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 214/214 [00:00<00:00, 1999.45it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 214
Maximum total tokens : 209
Maximum response tokens : 92
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 7.36 GB
Reserved  : 9.45 GB
Max Allocated : 8.23 GB
Max Reserved  : 9.45 GB
==========================================



================================================
TRAINING U
================================================

================================================
TRAINING COMPLETE
Training time: 13.86 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 7.41 GB
Reserved  : 9.62 GB
Max Allocated : 9.09 GB
Max Reserved  : 9.62 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance']
Test samples: 92
================================================

Generation:   0%|          | 0/92 [00:00<?, ?it/s]

Before generate : 7.41 GB allocated | 9.62 GB reserved
After generate  : 7.41 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 67
Maximum So Far : 67
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  11%|█         | 10/92 [00:23<03:22,  2.47s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 75
Maximum So Far : 95
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  22%|██▏       | 20/92 [00:48<03:04,  2.56s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved

Generation:  23%|██▎       | 21/92 [00:51<02:53,  2.44s/it]

After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 79
Maximum So Far : 97
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  33%|███▎      | 30/92 [01:09<01:57,  1.90s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 77
Maximum So Far : 97
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  43%|████▎     | 40/92 [01:31<01:56,  2.23s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 76
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  54%|█████▍    | 50/92 [01:54<01:40,  2.40s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 77
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  65%|██████▌   | 60/92 [02:17<01:14,  2.34s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved

Generation:  66%|██████▋   | 61/92 [02:19<01:08,  2.22s/it]

After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 79
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  76%|███████▌  | 70/92 [02:40<00:52,  2.40s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 95
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  87%|████████▋ | 80/92 [03:04<00:28,  2.36s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 85
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  98%|█████████▊| 90/92 [03:27<00:04,  2.31s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 96
Maximum So Far : 112
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation: 100%|██████████| 92/92 [03:32<00:00,  2.31s/it]

Saved -> SFT_U_qwen_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 2.05 GB
Reserved  : 7.10 GB
Max Allocated : 9.09 GB
Max Reserved  : 9.62 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C
INPUT COLUMNS: ['User Utterance', 'Context']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 2.05 GB
Reserved  : 7.10 GB
Max Allocated : 2.05 GB
Max Reserved  : 7.10 GB
==========================================


Loading FRESH model...

Loading weights: 100%|██████████| 339/339 [00:04<00:00, 76.45it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

================ MEMORY AFTER MODEL LOAD ================
Allocated : 9.41 GB
Reserved  : 11.51 GB
Max Allocated : 10.27 GB
Max Reserved  : 11.51 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 214/214 [00:00<00:00, 1633.11it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 214
Maximum total tokens : 325
Maximum response tokens : 92
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 9.41 GB
Reserved  : 11.51 GB
Max Allocated : 10.27 GB
Max Reserved  : 11.51 GB
==========================================



================================================
TRAINING U_C
================================================

================================================
TRAINING COMPLETE
Training time: 14.92 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 9.44 GB
Reserved  : 11.68 GB
Max Allocated : 11.33 GB
Max Reserved  : 11.68 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context']
Test samples: 92
================================================

Generation:   0%|          | 0/92 [00:00<?, ?it/s]

Before generate : 9.44 GB allocated | 11.68 GB reserved
After generate  : 9.44 GB allocated | 11.68 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 139
Maximum So Far : 139
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  11%|█         | 10/92 [00:24<03:21,  2.45s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 124
Maximum So Far : 179
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  22%|██▏       | 20/92 [00:49<02:54,  2.42s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 145
Maximum So Far : 179
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  33%|███▎      | 30/92 [01:12<02:08,  2.07s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 135
Maximum So Far : 184
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  43%|████▎     | 40/92 [01:34<02:05,  2.42s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved

Generation:  45%|████▍     | 41/92 [01:36<01:55,  2.27s/it]

After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 115
Maximum So Far : 184
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  54%|█████▍    | 50/92 [01:55<01:29,  2.13s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved

Generation:  55%|█████▌    | 51/92 [01:58<01:31,  2.24s/it]

After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 111
Maximum So Far : 184
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  65%|██████▌   | 60/92 [02:19<01:16,  2.41s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 121
Maximum So Far : 184
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  76%|███████▌  | 70/92 [02:41<00:49,  2.26s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 167
Maximum So Far : 184
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  87%|████████▋ | 80/92 [03:06<00:29,  2.43s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 181
Maximum So Far : 194
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  98%|█████████▊| 90/92 [03:29<00:04,  2.27s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 169
Maximum So Far : 241
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation: 100%|██████████| 92/92 [03:34<00:00,  2.33s/it]

Saved -> SFT_U_C_qwen_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 4.08 GB
Reserved  : 9.13 GB
Max Allocated : 11.33 GB
Max Reserved  : 11.68 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C_R
INPUT COLUMNS: ['User Utterance', 'Context', 'User Role', 'Model Role']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 4.08 GB
Reserved  : 9.13 GB
Max Allocated : 4.08 GB
Max Reserved  : 9.13 GB
==========================================


Loading FRESH model...

Loading weights: 100%|██████████| 339/339 [00:04<00:00, 77.37it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

================ MEMORY AFTER MODEL LOAD ================
Allocated : 11.44 GB
Reserved  : 13.54 GB
Max Allocated : 12.30 GB
Max Reserved  : 13.54 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 214/214 [00:00<00:00, 1644.63it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 214
Maximum total tokens : 339
Maximum response tokens : 92
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 11.44 GB
Reserved  : 13.54 GB
Max Allocated : 12.30 GB
Max Reserved  : 13.54 GB
==========================================



================================================
TRAINING U_C_R
================================================

================================================
TRAINING COMPLETE
Training time: 15.18 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 11.47 GB
Reserved  : 13.71 GB
Max Allocated : 13.38 GB
Max Reserved  : 13.71 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context', 'User Role', 'Model Role']
Test samples: 92
================================================

Generation:   0%|          | 0/92 [00:00<?, ?it/s]

Before generate : 11.47 GB allocated | 13.71 GB reserved
After generate  : 11.47 GB allocated | 13.71 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 153
Maximum So Far : 153
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  11%|█         | 10/92 [00:24<03:28,  2.54s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved

Generation:  12%|█▏        | 11/92 [00:26<03:23,  2.51s/it]

After generate  : 11.47 GB allocated | 13.62 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 139
Maximum So Far : 197
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  22%|██▏       | 20/92 [00:50<03:05,  2.58s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved
After generate  : 11.47 GB allocated | 13.62 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 163
Maximum So Far : 197
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  33%|███▎      | 30/92 [01:13<02:10,  2.10s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved
After generate  : 11.47 GB allocated | 13.62 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 155
Maximum So Far : 202
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  43%|████▎     | 40/92 [01:36<02:05,  2.42s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved
After generate  : 11.47 GB allocated | 13.62 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 129
Maximum So Far : 202
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  54%|█████▍    | 50/92 [02:00<01:43,  2.47s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved
After generate  : 11.47 GB allocated | 13.62 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 128
Maximum So Far : 202
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  65%|██████▌   | 60/92 [02:23<01:16,  2.38s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved

Generation:  66%|██████▋   | 61/92 [02:25<01:08,  2.20s/it]

After generate  : 11.47 GB allocated | 13.62 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 139
Maximum So Far : 202
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  76%|███████▌  | 70/92 [02:46<00:54,  2.46s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved
After generate  : 11.47 GB allocated | 13.62 GB reserved

Generation:  77%|███████▋  | 71/92 [02:49<00:52,  2.50s/it]

----------------------------------------
Sample         : 70
Prompt Tokens  : 185
Maximum So Far : 202
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  87%|████████▋ | 80/92 [03:12<00:31,  2.59s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved

Generation:  88%|████████▊ | 81/92 [03:15<00:28,  2.60s/it]

After generate  : 11.47 GB allocated | 13.63 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 195
Maximum So Far : 225
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation:  98%|█████████▊| 90/92 [03:37<00:04,  2.47s/it]

Before generate : 11.47 GB allocated | 13.62 GB reserved
After generate  : 11.47 GB allocated | 13.63 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 195
Maximum So Far : 265
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.62 GB
----------------------------------------

Generation: 100%|██████████| 92/92 [03:43<00:00,  2.43s/it]

Saved -> SFT_U_C_R_qwen_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 6.11 GB
Reserved  : 11.16 GB
Max Allocated : 13.38 GB
Max Reserved  : 13.71 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C_R_PD
INPUT COLUMNS: ['User Utterance', 'Context', 'User Role', 'Model Role', 'Power Distance']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 6.11 GB
Reserved  : 11.16 GB
Max Allocated : 6.11 GB
Max Reserved  : 11.16 GB
==========================================


Loading FRESH model...

Loading weights: 100%|██████████| 339/339 [00:04<00:00, 77.61it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

================ MEMORY AFTER MODEL LOAD ================
Allocated : 13.47 GB
Reserved  : 15.57 GB
Max Allocated : 14.33 GB
Max Reserved  : 15.57 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 214/214 [00:00<00:00, 1691.44it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 214
Maximum total tokens : 345
Maximum response tokens : 92
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 13.47 GB
Reserved  : 15.57 GB
Max Allocated : 14.33 GB
Max Reserved  : 15.57 GB
==========================================



================================================
TRAINING U_C_R_PD
================================================

================================================
TRAINING COMPLETE
Training time: 24.41 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 13.50 GB
Reserved  : 15.74 GB
Max Allocated : 15.42 GB
Max Reserved  : 15.74 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context', 'User Role', 'Model Role', 'Power Distance']
Test samples: 92
================================================

Generation:   0%|          | 0/92 [00:00<?, ?it/s]

Before generate : 13.50 GB allocated | 15.74 GB reserved
After generate  : 13.50 GB allocated | 15.74 GB reserved

Generation:   1%|          | 1/92 [00:03<04:59,  3.29s/it]

----------------------------------------
Sample         : 0
Prompt Tokens  : 159
Maximum So Far : 159
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  11%|█         | 10/92 [00:30<04:14,  3.10s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved

Generation:  12%|█▏        | 11/92 [00:33<04:16,  3.17s/it]

After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 145
Maximum So Far : 203
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  22%|██▏       | 20/92 [01:03<03:58,  3.32s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved

Generation:  23%|██▎       | 21/92 [01:07<03:54,  3.30s/it]

After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 169
Maximum So Far : 203
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  33%|███▎      | 30/92 [01:30<02:25,  2.35s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved
After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 161
Maximum So Far : 208
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  43%|████▎     | 40/92 [02:00<02:44,  3.16s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved
After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 135
Maximum So Far : 208
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  54%|█████▍    | 50/92 [02:29<02:12,  3.16s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved
After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 134
Maximum So Far : 208
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  65%|██████▌   | 60/92 [02:57<01:32,  2.89s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved
After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 145
Maximum So Far : 208
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  76%|███████▌  | 70/92 [03:26<01:06,  3.04s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved
After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 191
Maximum So Far : 208
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  87%|████████▋ | 80/92 [03:58<00:39,  3.27s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved
After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 201
Maximum So Far : 231
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation:  98%|█████████▊| 90/92 [04:29<00:06,  3.21s/it]

Before generate : 13.50 GB allocated | 15.66 GB reserved
After generate  : 13.50 GB allocated | 15.66 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 201
Maximum So Far : 271
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.66 GB
----------------------------------------

Generation: 100%|██████████| 92/92 [04:35<00:00,  3.00s/it]

Saved -> SFT_U_C_R_PD_qwen_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 8.14 GB
Reserved  : 13.20 GB
Max Allocated : 15.42 GB
Max Reserved  : 15.74 GB
==========================================




===========================================================================
ALL FOUR SFT EXPERIMENTS COMPLETED
===========================================================================

Generated files:
1. SFT_U_qwen_test.csv
2. SFT_U_C_qwen_test.csv
3. SFT_U_C_R_qwen_test.csv
4. SFT_U_C_R_PD_qwen_test.csv
===========================================================================