In [1]:
import os
import gc
import time
import warnings

import torch
import pandas as pd

from tqdm.auto import tqdm

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)

warnings.filterwarnings("ignore")


# ============================================================
# CONFIGURATION
# ============================================================

TRAIN_PATH = r"fewshot_examples.csv"
TEST_PATH  = r"P_CULTA_V2.csv"

MODEL_ID = "Qwen/Qwen2.5-7B-Instruct"

NUM_EPOCHS = 10

# Same general token setup as your previous generation code
MAX_LENGTH = 2048
MAX_NEW_TOKENS = 40


# ============================================================
# QLoRA CONFIGURATION
# ============================================================

LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05


# ============================================================
# TRAINING CONFIGURATION
# ============================================================

BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 8

LEARNING_RATE = 2e-4


# ============================================================
# LOAD DATA
# ============================================================

train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

print("==============================================")
print("DATASET")
print("==============================================")

print(f"Train shape : {train_df.shape}")
print(f"Test shape  : {test_df.shape}")

print("\nColumns:")
print(train_df.columns.tolist())

print("\n==============================================\n")


# ============================================================
# CHECK REQUIRED COLUMNS
# ============================================================

required_columns = [
    "User Utterance",
    "Context",
    "User Role",
    "Model Role",
    "Power Distance",
    "Gold Response",
]

for col in required_columns:

    if col not in train_df.columns:

        raise ValueError(
            f"Missing column in training file: {col}"
        )

    if col != "Gold Response" and col not in test_df.columns:

        raise ValueError(
            f"Missing column in test file: {col}"
        )


# ============================================================
# GPU CHECK
# ============================================================

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU not available."
    )


print("\n================ GPU INFO ================")

print(
    f"GPU : {torch.cuda.get_device_name(0)}"
)

props = torch.cuda.get_device_properties(0)

print(
    f"Total VRAM : "
    f"{props.total_memory / 1024**3:.2f} GB"
)

print(
    f"Allocated : "
    f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB"
)

print(
    f"Reserved  : "
    f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB"
)

print("==========================================\n")


# ============================================================
# SYSTEM INSTRUCTION
# ============================================================
#
# This is intentionally the SAME instruction used
# during your prompting experiments.
#
# There are NO demonstrations here.
#
# ============================================================

SYSTEM_INSTRUCTION = (
    "Generate a natural Urdu response. "
    "Output only the response utterance. "
    "Do not explain. "
    "Do not narrate. "
    "Do not add extra context. "
    "Do not ask unnecessary follow-up questions."
)


# ============================================================
# 4-BIT QUANTIZATION
# ============================================================

bnb_config = BitsAndBytesConfig(

    load_in_4bit=True,

    bnb_4bit_use_double_quant=True,

    bnb_4bit_quant_type="nf4",

    bnb_4bit_compute_dtype=torch.float16,
)


# ============================================================
# MEMORY PRINT FUNCTION
# ============================================================

def print_memory(title):

    print(
        f"\n================ {title} ================"
    )

    print(
        f"Allocated : "
        f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB"
    )

    print(
        f"Reserved  : "
        f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB"
    )

    print(
        f"Max Allocated : "
        f"{torch.cuda.max_memory_allocated() / 1024**3:.2f} GB"
    )

    print(
        f"Max Reserved  : "
        f"{torch.cuda.max_memory_reserved() / 1024**3:.2f} GB"
    )

    print("==========================================\n")


# ============================================================
# GPU CLEANUP
# ============================================================

def cleanup_gpu():

    gc.collect()

    if torch.cuda.is_available():

        torch.cuda.empty_cache()

        try:

            torch.cuda.ipc_collect()

        except Exception:

            pass


# ============================================================
# LOAD FRESH QWEN MODEL
# ============================================================
#
# IMPORTANT:
# A completely fresh Qwen model is loaded for every
# experiment.
#
# trust_remote_code=False prevents Transformers from
# trying to download custom_generate/generate.py.
#
# ============================================================

def load_fresh_model():

    print("\nLoading FRESH Qwen model...")

    # --------------------------------------------------------
    # MODEL
    # --------------------------------------------------------

    model = AutoModelForCausalLM.from_pretrained(

        MODEL_ID,

        quantization_config=bnb_config,

        device_map="auto",

        # IMPORTANT FIX
        trust_remote_code=False,
    )

    # --------------------------------------------------------
    # TOKENIZER
    # --------------------------------------------------------

    tokenizer = AutoTokenizer.from_pretrained(

        MODEL_ID,

        # IMPORTANT FIX
        trust_remote_code=False,
    )

    # --------------------------------------------------------
    # PAD TOKEN
    # --------------------------------------------------------

    if tokenizer.pad_token is None:

        tokenizer.pad_token = tokenizer.eos_token

    model.config.pad_token_id = tokenizer.pad_token_id

    # --------------------------------------------------------
    # PREPARE 4-BIT MODEL FOR TRAINING
    # --------------------------------------------------------

    model = prepare_model_for_kbit_training(
        model
    )

    # --------------------------------------------------------
    # LoRA
    # --------------------------------------------------------

    lora_config = LoraConfig(

        r=LORA_R,

        lora_alpha=LORA_ALPHA,

        lora_dropout=LORA_DROPOUT,

        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],

        bias="none",

        task_type="CAUSAL_LM",
    )

    model = get_peft_model(

        model,

        lora_config,
    )

    # --------------------------------------------------------
    # TRAINABLE PARAMETERS
    # --------------------------------------------------------

    model.print_trainable_parameters()

    print_memory(
        "MEMORY AFTER MODEL LOAD"
    )

    return model, tokenizer


# ============================================================
# BUILD USER CONTENT
# ============================================================

def build_user_content(
    row,
    input_columns,
):

    parts = []

    for col in input_columns:

        value = row[col]

        if pd.isna(value):

            value = ""

        value = str(value).strip()

        parts.append(
            f'{col}: "{value}"'
        )

    return "\n\n".join(parts)


# ============================================================
# PREPARE SFT DATA
# ============================================================
#
# TRAINING FORMAT:
#
# SYSTEM
# USER
# ASSISTANT = GOLD RESPONSE
#
# Loss is calculated ONLY on the response.
#
# ============================================================

def prepare_training_dataset(
    df,
    input_columns,
    tokenizer,
):

    dataset = []

    max_total_tokens = 0

    max_response_tokens = 0

    print(
        "\nBuilding training examples..."
    )

    for _, row in tqdm(

        df.iterrows(),

        total=len(df),

        desc="Preparing SFT data",

    ):

        # ----------------------------------------------------
        # USER INPUT
        # ----------------------------------------------------

        user_content = build_user_content(

            row,

            input_columns,
        )

        # ----------------------------------------------------
        # GOLD RESPONSE
        # ----------------------------------------------------

        gold_response = row[
            "Gold Response"
        ]

        if pd.isna(gold_response):

            gold_response = ""

        gold_response = str(
            gold_response
        ).strip()

        # ----------------------------------------------------
        # PROMPT ONLY
        # ----------------------------------------------------

        prompt_messages = [

            {
                "role": "system",
                "content": SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",
                "content": user_content,
            },
        ]

        prompt_text = tokenizer.apply_chat_template(

            prompt_messages,

            tokenize=False,

            add_generation_prompt=True,
        )

        # ----------------------------------------------------
        # FULL TRAINING EXAMPLE
        # ----------------------------------------------------

        full_messages = [

            {
                "role": "system",
                "content": SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",
                "content": user_content,
            },

            {
                "role": "assistant",
                "content": gold_response,
            },
        ]

        full_text = tokenizer.apply_chat_template(

            full_messages,

            tokenize=False,

            add_generation_prompt=False,
        )

        # ----------------------------------------------------
        # TOKENIZE PROMPT
        # ----------------------------------------------------

        prompt_tokens = tokenizer(

            prompt_text,

            add_special_tokens=False,

        )["input_ids"]

        prompt_length = len(
            prompt_tokens
        )

        # ----------------------------------------------------
        # TOKENIZE FULL SEQUENCE
        # ----------------------------------------------------

        full_tokens = tokenizer(

            full_text,

            add_special_tokens=False,

            truncation=True,

            max_length=MAX_LENGTH,
        )

        input_ids = full_tokens[
            "input_ids"
        ]

        attention_mask = full_tokens[
            "attention_mask"
        ]

        # ----------------------------------------------------
        # LABELS
        #
        # Prompt tokens = -100
        #
        # Gold response tokens = actual token IDs
        #
        # Therefore loss is only calculated on response.
        # ----------------------------------------------------

        labels = []

        for token_index in range(
            len(input_ids)
        ):

            if token_index < prompt_length:

                labels.append(-100)

            else:

                labels.append(
                    input_ids[token_index]
                )

        # ----------------------------------------------------
        # STATISTICS
        # ----------------------------------------------------

        response_length = max(

            0,

            len(input_ids) - prompt_length
        )

        max_total_tokens = max(

            max_total_tokens,

            len(input_ids)
        )

        max_response_tokens = max(

            max_response_tokens,

            response_length
        )

        # ----------------------------------------------------
        # ADD EXAMPLE
        # ----------------------------------------------------

        dataset.append({

            "input_ids": input_ids,

            "attention_mask": attention_mask,

            "labels": labels,

        })

    # --------------------------------------------------------
    # PRINT STATISTICS
    # --------------------------------------------------------

    print(
        f"\nTraining examples : "
        f"{len(dataset)}"
    )

    print(
        f"Maximum total tokens : "
        f"{max_total_tokens}"
    )

    print(
        f"Maximum response tokens : "
        f"{max_response_tokens}"
    )

    print(
        f"MAX_LENGTH : "
        f"{MAX_LENGTH}"
    )

    return dataset


# ============================================================
# PYTORCH DATASET
# ============================================================

class SFTDataset(
    torch.utils.data.Dataset
):

    def __init__(
        self,
        data,
    ):

        self.data = data

    def __len__(self):

        return len(self.data)

    def __getitem__(
        self,
        idx,
    ):

        return self.data[idx]


# ============================================================
# GENERATE TEST RESPONSES
# ============================================================

def generate_test_responses(

    model,

    tokenizer,

    test_df,

    input_columns,

    output_path,

):

    model.eval()

    responses = []

    max_tokens_seen = 0

    print(
        "\n================================================"
    )

    print(
        "GENERATING TEST RESPONSES"
    )

    print(
        f"Input columns: {input_columns}"
    )

    print(
        f"Test samples: {len(test_df)}"
    )

    print(
        "================================================\n"
    )

    for i, row in tqdm(

        test_df.iterrows(),

        total=len(test_df),

        desc="Generation",

    ):

        # ----------------------------------------------------
        # BUILD INPUT
        # ----------------------------------------------------

        user_content = build_user_content(

            row,

            input_columns,
        )

        # ----------------------------------------------------
        # TEST PROMPT
        # ----------------------------------------------------

        messages = [

            {
                "role": "system",

                "content":
                    SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",

                "content":
                    user_content,
            },
        ]

        # ----------------------------------------------------
        # CHAT TEMPLATE
        # ----------------------------------------------------

        text_in = tokenizer.apply_chat_template(

            messages,

            tokenize=False,

            add_generation_prompt=True,
        )

        # ----------------------------------------------------
        # TOKEN COUNT
        # ----------------------------------------------------

        num_tokens = len(

            tokenizer(
                text_in
            )["input_ids"]
        )

        max_tokens_seen = max(

            max_tokens_seen,

            num_tokens,
        )

        # ----------------------------------------------------
        # TOKENIZE
        # ----------------------------------------------------

        inputs = tokenizer(

            text_in,

            return_tensors="pt",

            truncation=True,

            max_length=MAX_LENGTH,
        )

        # Move inputs to model's device
        inputs = {
            key: value.to(model.device)
            for key, value in inputs.items()
        }

        # ----------------------------------------------------
        # GENERATION
        # ----------------------------------------------------

        with torch.no_grad():

            if i % 10 == 0:

                print(

                    f"\nBefore generate : "

                    f"{torch.cuda.memory_allocated()/1024**3:.2f} GB allocated | "

                    f"{torch.cuda.memory_reserved()/1024**3:.2f} GB reserved"
                )

            outputs = model.generate(

                **inputs,

                max_new_tokens=MAX_NEW_TOKENS,

                temperature=0.3,

                do_sample=True,

                repetition_penalty=1.1,

                pad_token_id=
                    tokenizer.eos_token_id,

                use_cache=True,
            )

            if i % 10 == 0:

                print(

                    f"After generate  : "

                    f"{torch.cuda.memory_allocated()/1024**3:.2f} GB allocated | "

                    f"{torch.cuda.memory_reserved()/1024**3:.2f} GB reserved"
                )

        # ----------------------------------------------------
        # REMOVE INPUT TOKENS
        # ----------------------------------------------------

        new_tokens = outputs[

            0

        ][

            inputs["input_ids"].shape[1]:
        ]

        # ----------------------------------------------------
        # DECODE RESPONSE
        # ----------------------------------------------------

        response = tokenizer.decode(

            new_tokens,

            skip_special_tokens=True,
        ).strip()

        responses.append(
            response
        )

        # ----------------------------------------------------
        # FREE MEMORY
        # ----------------------------------------------------

        del outputs

        del new_tokens

        del inputs

        gc.collect()

        torch.cuda.empty_cache()

        # ----------------------------------------------------
        # DIAGNOSTICS
        # ----------------------------------------------------

        if i % 10 == 0:

            print(
                "\n----------------------------------------"
            )

            print(
                f"Sample         : {i}"
            )

            print(
                f"Prompt Tokens  : {num_tokens}"
            )

            print(
                f"Maximum So Far : {max_tokens_seen}"
            )

            print(
                f"Allocated VRAM : "
                f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
            )

            print(
                f"Reserved VRAM  : "
                f"{torch.cuda.memory_reserved()/1024**3:.2f} GB"
            )

            print(
                "----------------------------------------"
            )

        # ----------------------------------------------------
        # BACKUP EVERY 25 SAMPLES
        # ----------------------------------------------------

        if i % 25 == 0 and i > 0:

            backup = test_df.copy()

            backup[
                "Qwen_Response"
            ] = (

                responses
                + [""] * (

                    len(test_df)
                    - len(responses)
                )
            )

            backup.to_csv(

                output_path.replace(

                    ".csv",

                    "_backup.csv",
                ),

                index=False,

                encoding="utf-8-sig",
            )

    # ========================================================
    # FINAL SAVE
    # ========================================================

    result = test_df.copy()

    result[
        "Qwen_Response"
    ] = responses

    result.to_csv(

        output_path,

        index=False,

        encoding="utf-8-sig",
    )

    print(
        f"\nSaved -> {output_path}"
    )

    return result


# ============================================================
# RUN ONE COMPLETE SFT EXPERIMENT
# ============================================================

def run_sft_experiment(

    experiment_name,

    input_columns,

    output_path,
):

    print("\n\n")

    print("=" * 75)

    print(
        f"STARTING SFT EXPERIMENT: "
        f"{experiment_name}"
    )

    print(
        f"INPUT COLUMNS: "
        f"{input_columns}"
    )

    print(
        f"EPOCHS: "
        f"{NUM_EPOCHS}"
    )

    print("=" * 75)

    # --------------------------------------------------------
    # CLEAN GPU
    # --------------------------------------------------------

    cleanup_gpu()

    torch.cuda.reset_peak_memory_stats()

    print_memory(
        "MEMORY BEFORE MODEL LOAD"
    )

    # --------------------------------------------------------
    # FRESH MODEL
    # --------------------------------------------------------

    model, tokenizer = (
        load_fresh_model()
    )

    # --------------------------------------------------------
    # PREPARE TRAIN DATA
    # --------------------------------------------------------

    train_data = (
        prepare_training_dataset(

            train_df,

            input_columns,

            tokenizer,
        )
    )

    train_dataset = SFTDataset(
        train_data
    )

    # --------------------------------------------------------
    # DATA COLLATOR
    # --------------------------------------------------------

    data_collator = DataCollatorForSeq2Seq(

        tokenizer=tokenizer,

        padding=True,

        return_tensors="pt",
    )

    print_memory(
        "MEMORY BEFORE TRAINING"
    )

    # --------------------------------------------------------
    # TRAINING ARGUMENTS
    # --------------------------------------------------------

    training_args = TrainingArguments(

        output_dir=(
            f"./sft_{experiment_name}"
        ),

        num_train_epochs=NUM_EPOCHS,

        per_device_train_batch_size=
            BATCH_SIZE,

        gradient_accumulation_steps=
            GRADIENT_ACCUMULATION,

        learning_rate=
            LEARNING_RATE,

        fp16=True,

        optim="paged_adamw_8bit",

        logging_steps=1,

        save_strategy="no",

        report_to="none",

        remove_unused_columns=False,

        gradient_checkpointing=True,

        max_grad_norm=0.3,

        warmup_ratio=0.03,

        lr_scheduler_type="cosine",
    )

    # --------------------------------------------------------
    # TRAINER
    # --------------------------------------------------------

    trainer = Trainer(

        model=model,

        args=training_args,

        train_dataset=train_dataset,

        data_collator=data_collator,
    )

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    print("\n")

    print(
        "================================================"
    )

    print(
        f"TRAINING {experiment_name}"
    )

    print(
        "================================================"
    )

    start_time = time.time()

    trainer.train()

    training_time = (
        time.time()
        - start_time
    )

    print(
        "\n================================================"
    )

    print(
        "TRAINING COMPLETE"
    )

    print(
        f"Training time: "
        f"{training_time / 60:.2f} minutes"
    )

    print(
        "================================================"
    )

    print_memory(
        "MEMORY AFTER TRAINING"
    )

    # --------------------------------------------------------
    # GENERATE TEST
    # --------------------------------------------------------

    result = generate_test_responses(

        model=model,

        tokenizer=tokenizer,

        test_df=test_df,

        input_columns=input_columns,

        output_path=output_path,
    )

    # --------------------------------------------------------
    # CLEANUP
    # --------------------------------------------------------

    print(
        "\nCleaning up model..."
    )

    del trainer

    del model

    del tokenizer

    del train_dataset

    del train_data

    cleanup_gpu()

    print_memory(
        "FINAL MEMORY AFTER CLEANUP"
    )

    return result


# ============================================================
# EXPERIMENT 1
# U
# ============================================================

result_U = run_sft_experiment(

    experiment_name="U",

    input_columns=[
        "User Utterance"
    ],

    output_path=(
        r"51_SFT_U_Qwen_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 2
# U + CONTEXT
# ============================================================

result_UC = run_sft_experiment(

    experiment_name="U_C",

    input_columns=[
        "User Utterance",
        "Context",
    ],

    output_path=(
        r"51_SFT_U_C_Qwen_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 3
# U + CONTEXT + ROLES
# ============================================================

result_UCR = run_sft_experiment(

    experiment_name="U_C_R",

    input_columns=[
        "User Utterance",
        "Context",
        "User Role",
        "Model Role",
    ],

    output_path=(
        r"51_SFT_U_C_R_Qwen_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 4
# U + CONTEXT + ROLES + POWER DISTANCE
# ============================================================

result_UCRPD = run_sft_experiment(

    experiment_name="U_C_R_PD",

    input_columns=[
        "User Utterance",
        "Context",
        "User Role",
        "Model Role",
        "Power Distance",
    ],

    output_path=(
        r"51_SFT_U_C_R_PD_Qwen_test.csv"
    ),
)


# ============================================================
# DONE
# ============================================================

print("\n\n")

print("=" * 75)

print(
    "ALL FOUR SFT EXPERIMENTS COMPLETED"
)

print("=" * 75)

print(
    "\nGenerated files:"
)

print(
    r"1. 51_SFT_U_Qwen_test.csv"
)

print(
    r"2. 51_SFT_U_C_Qwen_test.csv"
)

print(
    r"3. 51_SFT_U_C_R_Qwen_test.csv"
)

print(
    r"4. 51_SFT_U_C_R_PD_Qwen_test.csv"
)

print("=" * 75)

D:\stdFurqan\FYP_AA\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

==============================================
DATASET
==============================================
Train shape : (51, 11)
Test shape  : (255, 11)

Columns:
['Language', 'Topic', 'User Role', 'Model Role', 'Power Distance', 'Register', 'Pragmatic Genre', 'Sensitivity', 'User Utterance', 'Context', 'Gold Response']

==============================================


================ GPU INFO ================
GPU : NVIDIA GeForce RTX 4080 SUPER
Total VRAM : 15.99 GB
Allocated : 0.00 GB
Reserved  : 0.00 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U
INPUT COLUMNS: ['User Utterance']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 0.00 GB
Reserved  : 0.00 GB
Max Allocated : 0.00 GB
Max Reserved  : 0.00 GB
==========================================


Loading FRESH Qwen model...

Loading weights: 100%|██████████| 339/339 [00:17<00:00, 19.84it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

================ MEMORY AFTER MODEL LOAD ================
Allocated : 7.36 GB
Reserved  : 9.45 GB
Max Allocated : 8.23 GB
Max Reserved  : 9.45 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 51/51 [00:00<00:00, 1307.62it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 51
Maximum total tokens : 209
Maximum response tokens : 92
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 7.36 GB
Reserved  : 9.45 GB
Max Allocated : 8.23 GB
Max Reserved  : 9.45 GB
==========================================



================================================
TRAINING U
================================================

================================================
TRAINING COMPLETE
Training time: 3.39 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 7.41 GB
Reserved  : 9.62 GB
Max Allocated : 9.08 GB
Max Reserved  : 9.62 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s]

Before generate : 7.41 GB allocated | 9.62 GB reserved
After generate  : 7.41 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 79
Maximum So Far : 79
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:   4%|▍         | 10/255 [00:21<08:51,  2.17s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 78
Maximum So Far : 93
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:   8%|▊         | 20/255 [00:45<09:24,  2.40s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 75
Maximum So Far : 93
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  12%|█▏        | 30/255 [01:08<07:54,  2.11s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 64
Maximum So Far : 95
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  16%|█▌        | 40/255 [01:32<08:51,  2.47s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 85
Maximum So Far : 95
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  20%|█▉        | 50/255 [01:55<08:20,  2.44s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 65
Maximum So Far : 95
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  24%|██▎       | 60/255 [02:19<07:50,  2.41s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 71
Maximum So Far : 97
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  27%|██▋       | 70/255 [02:41<06:35,  2.14s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 91
Maximum So Far : 97
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  31%|███▏      | 80/255 [03:05<06:49,  2.34s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 71
Maximum So Far : 97
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  35%|███▌      | 90/255 [03:29<06:26,  2.34s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 71
Maximum So Far : 97
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  39%|███▉      | 100/255 [03:53<05:53,  2.28s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 77
Maximum So Far : 97
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  43%|████▎     | 110/255 [04:16<05:39,  2.34s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 77
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  47%|████▋     | 120/255 [04:38<05:02,  2.24s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 85
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  51%|█████     | 130/255 [05:02<05:04,  2.44s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 88
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  55%|█████▍    | 140/255 [05:26<04:36,  2.40s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 79
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  59%|█████▉    | 150/255 [05:48<03:51,  2.21s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 88
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  63%|██████▎   | 160/255 [06:10<03:28,  2.20s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 87
Maximum So Far : 98
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  67%|██████▋   | 170/255 [06:34<03:21,  2.37s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 78
Maximum So Far : 101
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  71%|███████   | 180/255 [06:56<02:47,  2.23s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 78
Maximum So Far : 101
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  75%|███████▍  | 190/255 [07:20<02:28,  2.28s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 76
Maximum So Far : 101
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  78%|███████▊  | 200/255 [07:44<02:12,  2.40s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 93
Maximum So Far : 101
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  82%|████████▏ | 210/255 [08:07<01:46,  2.36s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 70
Maximum So Far : 101
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  86%|████████▋ | 220/255 [08:30<01:24,  2.41s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved

Generation:  87%|████████▋ | 221/255 [08:31<01:11,  2.12s/it]

After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 67
Maximum So Far : 101
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  90%|█████████ | 230/255 [08:52<00:59,  2.40s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 93
Maximum So Far : 107
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  94%|█████████▍| 240/255 [09:16<00:36,  2.46s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 89
Maximum So Far : 107
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation:  98%|█████████▊| 250/255 [09:41<00:12,  2.47s/it]

Before generate : 7.41 GB allocated | 9.54 GB reserved
After generate  : 7.41 GB allocated | 9.54 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 90
Maximum So Far : 107
Allocated VRAM : 7.41 GB
Reserved VRAM  : 9.54 GB
----------------------------------------

Generation: 100%|██████████| 255/255 [09:52<00:00,  2.32s/it]

Saved -> 51_SFT_U_Qwen_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 2.05 GB
Reserved  : 7.10 GB
Max Allocated : 9.08 GB
Max Reserved  : 9.62 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C
INPUT COLUMNS: ['User Utterance', 'Context']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 2.05 GB
Reserved  : 7.10 GB
Max Allocated : 2.05 GB
Max Reserved  : 7.10 GB
==========================================


Loading FRESH Qwen model...

Loading weights: 100%|██████████| 339/339 [00:04<00:00, 78.76it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

================ MEMORY AFTER MODEL LOAD ================
Allocated : 9.41 GB
Reserved  : 11.48 GB
Max Allocated : 10.27 GB
Max Reserved  : 11.48 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 51/51 [00:00<00:00, 1593.73it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 51
Maximum total tokens : 325
Maximum response tokens : 92
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 9.41 GB
Reserved  : 11.48 GB
Max Allocated : 10.27 GB
Max Reserved  : 11.48 GB
==========================================



================================================
TRAINING U_C
================================================

================================================
TRAINING COMPLETE
Training time: 3.76 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 9.44 GB
Reserved  : 11.65 GB
Max Allocated : 11.32 GB
Max Reserved  : 11.65 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s]

Before generate : 9.44 GB allocated | 11.65 GB reserved
After generate  : 9.44 GB allocated | 11.65 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 134
Maximum So Far : 134
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:   4%|▍         | 10/255 [00:23<10:04,  2.47s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 138
Maximum So Far : 156
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:   8%|▊         | 20/255 [00:46<09:14,  2.36s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 150
Maximum So Far : 156
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  12%|█▏        | 30/255 [01:08<08:12,  2.19s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 130
Maximum So Far : 179
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  16%|█▌        | 40/255 [01:31<08:47,  2.45s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 130
Maximum So Far : 179
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  20%|█▉        | 50/255 [01:53<07:08,  2.09s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 123
Maximum So Far : 179
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  24%|██▎       | 60/255 [02:16<07:14,  2.23s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 124
Maximum So Far : 179
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  27%|██▋       | 70/255 [02:40<07:01,  2.28s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 160
Maximum So Far : 179
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  31%|███▏      | 80/255 [03:04<07:17,  2.50s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 153
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  35%|███▌      | 90/255 [03:27<06:32,  2.38s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 130
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  39%|███▉      | 100/255 [03:50<05:25,  2.10s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 137
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  43%|████▎     | 110/255 [04:13<05:49,  2.41s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 132
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  47%|████▋     | 120/255 [04:36<04:53,  2.17s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 128
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  51%|█████     | 130/255 [04:59<04:33,  2.19s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 151
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  55%|█████▍    | 140/255 [05:23<04:36,  2.40s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 125
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  59%|█████▉    | 150/255 [05:45<03:51,  2.20s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 129
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  63%|██████▎   | 160/255 [06:05<03:16,  2.07s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 147
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  67%|██████▋   | 170/255 [06:28<03:14,  2.29s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 114
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  71%|███████   | 180/255 [06:51<02:59,  2.39s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 121
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  75%|███████▍  | 190/255 [07:16<02:39,  2.45s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 111
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  78%|███████▊  | 200/255 [07:40<02:15,  2.47s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 154
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  82%|████████▏ | 210/255 [08:02<01:33,  2.08s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 116
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  86%|████████▋ | 220/255 [08:23<01:17,  2.21s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 112
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  90%|█████████ | 230/255 [08:43<00:56,  2.26s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved

Generation:  91%|█████████ | 231/255 [08:45<00:55,  2.33s/it]

After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 149
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  94%|█████████▍| 240/255 [09:05<00:36,  2.41s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 146
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation:  98%|█████████▊| 250/255 [09:28<00:11,  2.34s/it]

Before generate : 9.44 GB allocated | 11.57 GB reserved
After generate  : 9.44 GB allocated | 11.57 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 156
Maximum So Far : 204
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.57 GB
----------------------------------------

Generation: 100%|██████████| 255/255 [09:40<00:00,  2.28s/it]

Saved -> 51_SFT_U_C_Qwen_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 4.08 GB
Reserved  : 9.13 GB
Max Allocated : 11.32 GB
Max Reserved  : 11.65 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C_R
INPUT COLUMNS: ['User Utterance', 'Context', 'User Role', 'Model Role']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 4.08 GB
Reserved  : 9.13 GB
Max Allocated : 4.08 GB
Max Reserved  : 9.13 GB
==========================================


Loading FRESH Qwen model...

Loading weights: 100%|██████████| 339/339 [00:04<00:00, 78.22it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

================ MEMORY AFTER MODEL LOAD ================
Allocated : 11.44 GB
Reserved  : 13.51 GB
Max Allocated : 12.31 GB
Max Reserved  : 13.51 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 51/51 [00:00<00:00, 1437.53it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 51
Maximum total tokens : 339
Maximum response tokens : 92
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 11.44 GB
Reserved  : 13.51 GB
Max Allocated : 12.31 GB
Max Reserved  : 13.51 GB
==========================================



================================================
TRAINING U_C_R
================================================

================================================
TRAINING COMPLETE
Training time: 3.91 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 11.47 GB
Reserved  : 13.68 GB
Max Allocated : 13.39 GB
Max Reserved  : 13.68 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context', 'User Role', 'Model Role']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s]

Before generate : 11.47 GB allocated | 13.68 GB reserved
After generate  : 11.47 GB allocated | 13.68 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 151
Maximum So Far : 151
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:   4%|▍         | 10/255 [00:22<09:49,  2.41s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 155
Maximum So Far : 172
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:   8%|▊         | 20/255 [00:45<08:56,  2.29s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 164
Maximum So Far : 174
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  12%|█▏        | 30/255 [01:07<08:45,  2.34s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 146
Maximum So Far : 197
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  16%|█▌        | 40/255 [01:30<08:19,  2.32s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved

Generation:  16%|█▌        | 41/255 [01:32<07:49,  2.20s/it]

After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 148
Maximum So Far : 197
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  20%|█▉        | 50/255 [01:54<08:18,  2.43s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 137
Maximum So Far : 197
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  24%|██▎       | 60/255 [02:19<07:44,  2.38s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 148
Maximum So Far : 197
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  27%|██▋       | 70/255 [02:42<06:49,  2.21s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 176
Maximum So Far : 197
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  31%|███▏      | 80/255 [03:05<06:53,  2.36s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 173
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  35%|███▌      | 90/255 [03:28<06:31,  2.37s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 145
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  39%|███▉      | 100/255 [03:53<06:29,  2.51s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 160
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  43%|████▎     | 110/255 [04:17<05:58,  2.47s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 147
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  47%|████▋     | 120/255 [04:40<05:30,  2.45s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 146
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  51%|█████     | 130/255 [05:05<05:08,  2.47s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 167
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  55%|█████▍    | 140/255 [05:28<04:14,  2.21s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 139
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  59%|█████▉    | 150/255 [05:50<04:05,  2.34s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 143
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  63%|██████▎   | 160/255 [06:13<03:22,  2.13s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 161
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  67%|██████▋   | 170/255 [06:36<03:21,  2.38s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 128
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  71%|███████   | 180/255 [07:00<03:02,  2.43s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 135
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  75%|███████▍  | 190/255 [07:24<02:35,  2.39s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 125
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  78%|███████▊  | 200/255 [07:49<02:12,  2.41s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 172
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  82%|████████▏ | 210/255 [08:12<01:42,  2.29s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved

Generation:  83%|████████▎ | 211/255 [08:15<01:42,  2.32s/it]

After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 132
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  86%|████████▋ | 220/255 [08:35<01:22,  2.37s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved

Generation:  87%|████████▋ | 221/255 [08:36<01:11,  2.12s/it]

After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 128
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  90%|█████████ | 230/255 [08:57<00:59,  2.38s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 163
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  94%|█████████▍| 240/255 [09:21<00:37,  2.49s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 160
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation:  98%|█████████▊| 250/255 [09:45<00:11,  2.34s/it]

Before generate : 11.47 GB allocated | 13.59 GB reserved
After generate  : 11.47 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 170
Maximum So Far : 228
Allocated VRAM : 11.47 GB
Reserved VRAM  : 13.59 GB
----------------------------------------

Generation: 100%|██████████| 255/255 [09:57<00:00,  2.34s/it]

Saved -> 51_SFT_U_C_R_Qwen_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 6.11 GB
Reserved  : 11.16 GB
Max Allocated : 13.39 GB
Max Reserved  : 13.68 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C_R_PD
INPUT COLUMNS: ['User Utterance', 'Context', 'User Role', 'Model Role', 'Power Distance']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 6.11 GB
Reserved  : 11.16 GB
Max Allocated : 6.11 GB
Max Reserved  : 11.16 GB
==========================================


Loading FRESH Qwen model...

Loading weights: 100%|██████████| 339/339 [00:04<00:00, 78.15it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

================ MEMORY AFTER MODEL LOAD ================
Allocated : 13.48 GB
Reserved  : 15.54 GB
Max Allocated : 14.34 GB
Max Reserved  : 15.54 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 51/51 [00:00<00:00, 1436.17it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 51
Maximum total tokens : 345
Maximum response tokens : 92
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 13.48 GB
Reserved  : 15.54 GB
Max Allocated : 14.34 GB
Max Reserved  : 15.54 GB
==========================================



================================================
TRAINING U_C_R_PD
================================================

================================================
TRAINING COMPLETE
Training time: 6.18 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 13.50 GB
Reserved  : 15.72 GB
Max Allocated : 15.43 GB
Max Reserved  : 15.72 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context', 'User Role', 'Model Role', 'Power Distance']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s]

Before generate : 13.50 GB allocated | 15.72 GB reserved
After generate  : 13.50 GB allocated | 15.72 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 157
Maximum So Far : 157
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:   4%|▍         | 10/255 [00:29<12:48,  3.14s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 161
Maximum So Far : 178
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:   8%|▊         | 20/255 [00:59<12:30,  3.19s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 170
Maximum So Far : 180
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  12%|█▏        | 30/255 [01:29<11:09,  2.97s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 152
Maximum So Far : 203
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  16%|█▌        | 40/255 [02:00<11:03,  3.09s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 154
Maximum So Far : 203
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  20%|█▉        | 50/255 [02:30<09:54,  2.90s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 143
Maximum So Far : 203
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  24%|██▎       | 60/255 [03:01<10:15,  3.15s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 154
Maximum So Far : 203
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  27%|██▋       | 70/255 [03:32<09:13,  2.99s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 182
Maximum So Far : 203
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  31%|███▏      | 80/255 [04:02<08:46,  3.01s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 179
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  35%|███▌      | 90/255 [04:32<08:17,  3.02s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 151
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  39%|███▉      | 100/255 [05:05<07:54,  3.06s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 166
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  43%|████▎     | 110/255 [05:35<07:22,  3.05s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

Generation:  44%|████▎     | 111/255 [05:39<07:33,  3.15s/it]

----------------------------------------
Sample         : 110
Prompt Tokens  : 153
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  47%|████▋     | 120/255 [06:07<06:46,  3.01s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 152
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  51%|█████     | 130/255 [06:40<06:45,  3.24s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 173
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  55%|█████▍    | 140/255 [07:10<05:32,  2.89s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 145
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  59%|█████▉    | 150/255 [07:43<05:37,  3.22s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved

Generation:  59%|█████▉    | 151/255 [07:46<05:37,  3.25s/it]

After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 149
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  63%|██████▎   | 160/255 [08:14<04:56,  3.13s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

Generation:  63%|██████▎   | 161/255 [08:16<04:20,  2.78s/it]

----------------------------------------
Sample         : 160
Prompt Tokens  : 167
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  67%|██████▋   | 170/255 [08:43<04:24,  3.12s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

Generation:  67%|██████▋   | 171/255 [08:46<04:11,  3.00s/it]

----------------------------------------
Sample         : 170
Prompt Tokens  : 134
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  71%|███████   | 180/255 [09:14<04:01,  3.22s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 141
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  75%|███████▍  | 190/255 [09:45<03:19,  3.07s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 131
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  78%|███████▊  | 200/255 [10:19<03:00,  3.28s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 178
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  82%|████████▏ | 210/255 [10:48<02:10,  2.90s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 138
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  86%|████████▋ | 220/255 [11:16<01:48,  3.10s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 134
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  90%|█████████ | 230/255 [11:45<01:18,  3.15s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 169
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  94%|█████████▍| 240/255 [12:17<00:45,  3.03s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 166
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation:  98%|█████████▊| 250/255 [12:46<00:14,  2.99s/it]

Before generate : 13.50 GB allocated | 15.63 GB reserved
After generate  : 13.50 GB allocated | 15.63 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 176
Maximum So Far : 234
Allocated VRAM : 13.50 GB
Reserved VRAM  : 15.63 GB
----------------------------------------

Generation: 100%|██████████| 255/255 [13:03<00:00,  3.07s/it]

Saved -> 51_SFT_U_C_R_PD_Qwen_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 8.14 GB
Reserved  : 13.20 GB
Max Allocated : 15.43 GB
Max Reserved  : 15.72 GB
==========================================




===========================================================================
ALL FOUR SFT EXPERIMENTS COMPLETED
===========================================================================

Generated files:
1. 51_SFT_U_Qwen_test.csv
2. 51_SFT_U_C_Qwen_test.csv
3. 51_\SFT_U_C_R_Qwen_test.csv
4. 51_SFT_U_C_R_PD_Qwen_test.csv
===========================================================================