In [1]:
import os
import gc
import time
import warnings

import torch
import pandas as pd

from tqdm.auto import tqdm

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)

warnings.filterwarnings("ignore")


# ============================================================
# CONFIGURATION
# ============================================================

TRAIN_PATH = r"fewshot_examples_17_set3.csv"
TEST_PATH  = r"P_CULTA_V2.csv"

MODEL_ID = "meta-llama/Meta-Llama-3.1-8B-Instruct"

NUM_EPOCHS = 10

# Same general token setup as your previous generation code
MAX_LENGTH = 2048
MAX_NEW_TOKENS = 40


# ============================================================
# QLoRA CONFIGURATION
# ============================================================

LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05


# ============================================================
# TRAINING CONFIGURATION
# ============================================================

BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 8

LEARNING_RATE = 2e-4


# ============================================================
# LOAD DATA
# ============================================================

train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

print("==============================================")
print("DATASET")
print("==============================================")

print(f"Train shape : {train_df.shape}")
print(f"Test shape  : {test_df.shape}")

print("\nColumns:")
print(train_df.columns.tolist())

print("\n==============================================\n")


# ============================================================
# CHECK REQUIRED COLUMNS
# ============================================================

required_columns = [
    "User Utterance",
    "Context",
    "User Role",
    "Model Role",
    "Power Distance",
    "Gold Response",
]

for col in required_columns:

    if col not in train_df.columns:

        raise ValueError(
            f"Missing column in training file: {col}"
        )

    if col != "Gold Response" and col not in test_df.columns:

        raise ValueError(
            f"Missing column in test file: {col}"
        )


# ============================================================
# GPU CHECK
# ============================================================

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU not available."
    )


print("\n================ GPU INFO ================")

print(
    f"GPU : {torch.cuda.get_device_name(0)}"
)

props = torch.cuda.get_device_properties(0)

print(
    f"Total VRAM : "
    f"{props.total_memory / 1024**3:.2f} GB"
)

print(
    f"Allocated : "
    f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB"
)

print(
    f"Reserved  : "
    f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB"
)

print("==========================================\n")


# ============================================================
# SYSTEM INSTRUCTION
# ============================================================
#
# This is intentionally the SAME instruction used
# during your prompting experiments.
#
# There are NO demonstrations here.
#
# ============================================================

SYSTEM_INSTRUCTION = (
    "Generate a natural Urdu response. "
    "Output only the response utterance. "
    "Do not explain. "
    "Do not narrate. "
    "Do not add extra context. "
    "Do not ask unnecessary follow-up questions."
)


# ============================================================
# 4-BIT QUANTIZATION
# ============================================================

bnb_config = BitsAndBytesConfig(

    load_in_4bit=True,

    bnb_4bit_use_double_quant=True,

    bnb_4bit_quant_type="nf4",

    bnb_4bit_compute_dtype=torch.float16,
)


# ============================================================
# MEMORY PRINT FUNCTION
# ============================================================

def print_memory(title):

    print(
        f"\n================ {title} ================"
    )

    print(
        f"Allocated : "
        f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB"
    )

    print(
        f"Reserved  : "
        f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB"
    )

    print(
        f"Max Allocated : "
        f"{torch.cuda.max_memory_allocated() / 1024**3:.2f} GB"
    )

    print(
        f"Max Reserved  : "
        f"{torch.cuda.max_memory_reserved() / 1024**3:.2f} GB"
    )

    print("==========================================\n")


# ============================================================
# GPU CLEANUP
# ============================================================

def cleanup_gpu():

    gc.collect()

    if torch.cuda.is_available():

        torch.cuda.empty_cache()

        try:

            torch.cuda.ipc_collect()

        except Exception:

            pass


# ============================================================
# LOAD FRESH QWEN MODEL
# ============================================================
#
# IMPORTANT:
# A completely fresh Qwen model is loaded for every
# experiment.
#
# trust_remote_code=False prevents Transformers from
# trying to download custom_generate/generate.py.
#
# ============================================================

def load_fresh_model():

    print("\nLoading FRESH Qwen model...")

    # --------------------------------------------------------
    # MODEL
    # --------------------------------------------------------

    model = AutoModelForCausalLM.from_pretrained(

        MODEL_ID,

        quantization_config=bnb_config,

        device_map="auto",

        # IMPORTANT FIX
        trust_remote_code=False,
    )

    # --------------------------------------------------------
    # TOKENIZER
    # --------------------------------------------------------

    tokenizer = AutoTokenizer.from_pretrained(

        MODEL_ID,

        # IMPORTANT FIX
        trust_remote_code=False,
    )

    # --------------------------------------------------------
    # PAD TOKEN
    # --------------------------------------------------------

    if tokenizer.pad_token is None:

        tokenizer.pad_token = tokenizer.eos_token

    model.config.pad_token_id = tokenizer.pad_token_id

    # --------------------------------------------------------
    # PREPARE 4-BIT MODEL FOR TRAINING
    # --------------------------------------------------------

    model = prepare_model_for_kbit_training(
        model
    )

    # --------------------------------------------------------
    # LoRA
    # --------------------------------------------------------

    lora_config = LoraConfig(

        r=LORA_R,

        lora_alpha=LORA_ALPHA,

        lora_dropout=LORA_DROPOUT,

        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],

        bias="none",

        task_type="CAUSAL_LM",
    )

    model = get_peft_model(

        model,

        lora_config,
    )

    # --------------------------------------------------------
    # TRAINABLE PARAMETERS
    # --------------------------------------------------------

    model.print_trainable_parameters()

    print_memory(
        "MEMORY AFTER MODEL LOAD"
    )

    return model, tokenizer


# ============================================================
# BUILD USER CONTENT
# ============================================================

def build_user_content(
    row,
    input_columns,
):

    parts = []

    for col in input_columns:

        value = row[col]

        if pd.isna(value):

            value = ""

        value = str(value).strip()

        parts.append(
            f'{col}: "{value}"'
        )

    return "\n\n".join(parts)


# ============================================================
# PREPARE SFT DATA
# ============================================================
#
# TRAINING FORMAT:
#
# SYSTEM
# USER
# ASSISTANT = GOLD RESPONSE
#
# Loss is calculated ONLY on the response.
#
# ============================================================

def prepare_training_dataset(
    df,
    input_columns,
    tokenizer,
):

    dataset = []

    max_total_tokens = 0

    max_response_tokens = 0

    print(
        "\nBuilding training examples..."
    )

    for _, row in tqdm(

        df.iterrows(),

        total=len(df),

        desc="Preparing SFT data",

    ):

        # ----------------------------------------------------
        # USER INPUT
        # ----------------------------------------------------

        user_content = build_user_content(

            row,

            input_columns,
        )

        # ----------------------------------------------------
        # GOLD RESPONSE
        # ----------------------------------------------------

        gold_response = row[
            "Gold Response"
        ]

        if pd.isna(gold_response):

            gold_response = ""

        gold_response = str(
            gold_response
        ).strip()

        # ----------------------------------------------------
        # PROMPT ONLY
        # ----------------------------------------------------

        prompt_messages = [

            {
                "role": "system",
                "content": SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",
                "content": user_content,
            },
        ]

        prompt_text = tokenizer.apply_chat_template(

            prompt_messages,

            tokenize=False,

            add_generation_prompt=True,
        )

        # ----------------------------------------------------
        # FULL TRAINING EXAMPLE
        # ----------------------------------------------------

        full_messages = [

            {
                "role": "system",
                "content": SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",
                "content": user_content,
            },

            {
                "role": "assistant",
                "content": gold_response,
            },
        ]

        full_text = tokenizer.apply_chat_template(

            full_messages,

            tokenize=False,

            add_generation_prompt=False,
        )

        # ----------------------------------------------------
        # TOKENIZE PROMPT
        # ----------------------------------------------------

        prompt_tokens = tokenizer(

            prompt_text,

            add_special_tokens=False,

        )["input_ids"]

        prompt_length = len(
            prompt_tokens
        )

        # ----------------------------------------------------
        # TOKENIZE FULL SEQUENCE
        # ----------------------------------------------------

        full_tokens = tokenizer(

            full_text,

            add_special_tokens=False,

            truncation=True,

            max_length=MAX_LENGTH,
        )

        input_ids = full_tokens[
            "input_ids"
        ]

        attention_mask = full_tokens[
            "attention_mask"
        ]

        # ----------------------------------------------------
        # LABELS
        #
        # Prompt tokens = -100
        #
        # Gold response tokens = actual token IDs
        #
        # Therefore loss is only calculated on response.
        # ----------------------------------------------------

        labels = []

        for token_index in range(
            len(input_ids)
        ):

            if token_index < prompt_length:

                labels.append(-100)

            else:

                labels.append(
                    input_ids[token_index]
                )

        # ----------------------------------------------------
        # STATISTICS
        # ----------------------------------------------------

        response_length = max(

            0,

            len(input_ids) - prompt_length
        )

        max_total_tokens = max(

            max_total_tokens,

            len(input_ids)
        )

        max_response_tokens = max(

            max_response_tokens,

            response_length
        )

        # ----------------------------------------------------
        # ADD EXAMPLE
        # ----------------------------------------------------

        dataset.append({

            "input_ids": input_ids,

            "attention_mask": attention_mask,

            "labels": labels,

        })

    # --------------------------------------------------------
    # PRINT STATISTICS
    # --------------------------------------------------------

    print(
        f"\nTraining examples : "
        f"{len(dataset)}"
    )

    print(
        f"Maximum total tokens : "
        f"{max_total_tokens}"
    )

    print(
        f"Maximum response tokens : "
        f"{max_response_tokens}"
    )

    print(
        f"MAX_LENGTH : "
        f"{MAX_LENGTH}"
    )

    return dataset


# ============================================================
# PYTORCH DATASET
# ============================================================

class SFTDataset(
    torch.utils.data.Dataset
):

    def __init__(
        self,
        data,
    ):

        self.data = data

    def __len__(self):

        return len(self.data)

    def __getitem__(
        self,
        idx,
    ):

        return self.data[idx]


# ============================================================
# GENERATE TEST RESPONSES
# ============================================================

def generate_test_responses(

    model,

    tokenizer,

    test_df,

    input_columns,

    output_path,

):

    model.eval()

    responses = []

    max_tokens_seen = 0

    print(
        "\n================================================"
    )

    print(
        "GENERATING TEST RESPONSES"
    )

    print(
        f"Input columns: {input_columns}"
    )

    print(
        f"Test samples: {len(test_df)}"
    )

    print(
        "================================================\n"
    )

    for i, row in tqdm(

        test_df.iterrows(),

        total=len(test_df),

        desc="Generation",

    ):

        # ----------------------------------------------------
        # BUILD INPUT
        # ----------------------------------------------------

        user_content = build_user_content(

            row,

            input_columns,
        )

        # ----------------------------------------------------
        # TEST PROMPT
        # ----------------------------------------------------

        messages = [

            {
                "role": "system",

                "content":
                    SYSTEM_INSTRUCTION,
            },

            {
                "role": "user",

                "content":
                    user_content,
            },
        ]

        # ----------------------------------------------------
        # CHAT TEMPLATE
        # ----------------------------------------------------

        text_in = tokenizer.apply_chat_template(

            messages,

            tokenize=False,

            add_generation_prompt=True,
        )

        # ----------------------------------------------------
        # TOKEN COUNT
        # ----------------------------------------------------

        num_tokens = len(

            tokenizer(
                text_in
            )["input_ids"]
        )

        max_tokens_seen = max(

            max_tokens_seen,

            num_tokens,
        )

        # ----------------------------------------------------
        # TOKENIZE
        # ----------------------------------------------------

        inputs = tokenizer(

            text_in,

            return_tensors="pt",

            truncation=True,

            max_length=MAX_LENGTH,
        )

        # Move inputs to model's device
        inputs = {
            key: value.to(model.device)
            for key, value in inputs.items()
        }

        # ----------------------------------------------------
        # GENERATION
        # ----------------------------------------------------

        with torch.no_grad():

            if i % 10 == 0:

                print(

                    f"\nBefore generate : "

                    f"{torch.cuda.memory_allocated()/1024**3:.2f} GB allocated | "

                    f"{torch.cuda.memory_reserved()/1024**3:.2f} GB reserved"
                )

            outputs = model.generate(

                **inputs,

                max_new_tokens=MAX_NEW_TOKENS,

                temperature=0.3,

                do_sample=True,

                repetition_penalty=1.1,

                pad_token_id=
                    tokenizer.eos_token_id,

                use_cache=True,
            )

            if i % 10 == 0:

                print(

                    f"After generate  : "

                    f"{torch.cuda.memory_allocated()/1024**3:.2f} GB allocated | "

                    f"{torch.cuda.memory_reserved()/1024**3:.2f} GB reserved"
                )

        # ----------------------------------------------------
        # REMOVE INPUT TOKENS
        # ----------------------------------------------------

        new_tokens = outputs[

            0

        ][

            inputs["input_ids"].shape[1]:
        ]

        # ----------------------------------------------------
        # DECODE RESPONSE
        # ----------------------------------------------------

        response = tokenizer.decode(

            new_tokens,

            skip_special_tokens=True,
        ).strip()

        responses.append(
            response
        )

        # ----------------------------------------------------
        # FREE MEMORY
        # ----------------------------------------------------

        del outputs

        del new_tokens

        del inputs

        gc.collect()

        torch.cuda.empty_cache()

        # ----------------------------------------------------
        # DIAGNOSTICS
        # ----------------------------------------------------

        if i % 10 == 0:

            print(
                "\n----------------------------------------"
            )

            print(
                f"Sample         : {i}"
            )

            print(
                f"Prompt Tokens  : {num_tokens}"
            )

            print(
                f"Maximum So Far : {max_tokens_seen}"
            )

            print(
                f"Allocated VRAM : "
                f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
            )

            print(
                f"Reserved VRAM  : "
                f"{torch.cuda.memory_reserved()/1024**3:.2f} GB"
            )

            print(
                "----------------------------------------"
            )

        # ----------------------------------------------------
        # BACKUP EVERY 25 SAMPLES
        # ----------------------------------------------------

        if i % 25 == 0 and i > 0:

            backup = test_df.copy()

            backup[
                "LLaMA_Response"
            ] = (

                responses
                + [""] * (

                    len(test_df)
                    - len(responses)
                )
            )

            backup.to_csv(

                output_path.replace(

                    ".csv",

                    "_backup.csv",
                ),

                index=False,

                encoding="utf-8-sig",
            )

    # ========================================================
    # FINAL SAVE
    # ========================================================

    result = test_df.copy()

    result[
        "LLaMA_Response"
    ] = responses

    result.to_csv(

        output_path,

        index=False,

        encoding="utf-8-sig",
    )

    print(
        f"\nSaved -> {output_path}"
    )

    return result


# ============================================================
# RUN ONE COMPLETE SFT EXPERIMENT
# ============================================================

def run_sft_experiment(

    experiment_name,

    input_columns,

    output_path,
):

    print("\n\n")

    print("=" * 75)

    print(
        f"STARTING SFT EXPERIMENT: "
        f"{experiment_name}"
    )

    print(
        f"INPUT COLUMNS: "
        f"{input_columns}"
    )

    print(
        f"EPOCHS: "
        f"{NUM_EPOCHS}"
    )

    print("=" * 75)

    # --------------------------------------------------------
    # CLEAN GPU
    # --------------------------------------------------------

    cleanup_gpu()

    torch.cuda.reset_peak_memory_stats()

    print_memory(
        "MEMORY BEFORE MODEL LOAD"
    )

    # --------------------------------------------------------
    # FRESH MODEL
    # --------------------------------------------------------

    model, tokenizer = (
        load_fresh_model()
    )

    # --------------------------------------------------------
    # PREPARE TRAIN DATA
    # --------------------------------------------------------

    train_data = (
        prepare_training_dataset(

            train_df,

            input_columns,

            tokenizer,
        )
    )

    train_dataset = SFTDataset(
        train_data
    )

    # --------------------------------------------------------
    # DATA COLLATOR
    # --------------------------------------------------------

    data_collator = DataCollatorForSeq2Seq(

        tokenizer=tokenizer,

        padding=True,

        return_tensors="pt",
    )

    print_memory(
        "MEMORY BEFORE TRAINING"
    )

    # --------------------------------------------------------
    # TRAINING ARGUMENTS
    # --------------------------------------------------------

    training_args = TrainingArguments(

        output_dir=(
            f"./sft_{experiment_name}"
        ),

        num_train_epochs=NUM_EPOCHS,

        per_device_train_batch_size=
            BATCH_SIZE,

        gradient_accumulation_steps=
            GRADIENT_ACCUMULATION,

        learning_rate=
            LEARNING_RATE,

        fp16=True,

        optim="paged_adamw_8bit",

        logging_steps=1,

        save_strategy="no",

        report_to="none",

        remove_unused_columns=False,

        gradient_checkpointing=True,

        max_grad_norm=0.3,

        warmup_ratio=0.03,

        lr_scheduler_type="cosine",
    )

    # --------------------------------------------------------
    # TRAINER
    # --------------------------------------------------------

    trainer = Trainer(

        model=model,

        args=training_args,

        train_dataset=train_dataset,

        data_collator=data_collator,
    )

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    print("\n")

    print(
        "================================================"
    )

    print(
        f"TRAINING {experiment_name}"
    )

    print(
        "================================================"
    )

    start_time = time.time()

    trainer.train()

    training_time = (
        time.time()
        - start_time
    )

    print(
        "\n================================================"
    )

    print(
        "TRAINING COMPLETE"
    )

    print(
        f"Training time: "
        f"{training_time / 60:.2f} minutes"
    )

    print(
        "================================================"
    )

    print_memory(
        "MEMORY AFTER TRAINING"
    )

    # --------------------------------------------------------
    # GENERATE TEST
    # --------------------------------------------------------

    result = generate_test_responses(

        model=model,

        tokenizer=tokenizer,

        test_df=test_df,

        input_columns=input_columns,

        output_path=output_path,
    )

    # --------------------------------------------------------
    # CLEANUP
    # --------------------------------------------------------

    print(
        "\nCleaning up model..."
    )

    del trainer

    del model

    del tokenizer

    del train_dataset

    del train_data

    cleanup_gpu()

    print_memory(
        "FINAL MEMORY AFTER CLEANUP"
    )

    return result


# ============================================================
# EXPERIMENT 1
# U
# ============================================================

result_U = run_sft_experiment(

    experiment_name="U",

    input_columns=[
        "User Utterance"
    ],

    output_path=(
        r"Set3_SFT_U_llama_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 2
# U + CONTEXT
# ============================================================

result_UC = run_sft_experiment(

    experiment_name="U_C",

    input_columns=[
        "User Utterance",
        "Context",
    ],

    output_path=(
        r"Set3_SFT_U_C_llama_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 3
# U + CONTEXT + ROLES
# ============================================================

result_UCR = run_sft_experiment(

    experiment_name="U_C_R",

    input_columns=[
        "User Utterance",
        "Context",
        "User Role",
        "Model Role",
    ],

    output_path=(
        r"Set3_SFT_U_C_R_llama_test.csv"
    ),
)


# ============================================================
# EXPERIMENT 4
# U + CONTEXT + ROLES + POWER DISTANCE
# ============================================================

result_UCRPD = run_sft_experiment(

    experiment_name="U_C_R_PD",

    input_columns=[
        "User Utterance",
        "Context",
        "User Role",
        "Model Role",
        "Power Distance",
    ],

    output_path=(
        r"Set3_SFT_U_C_R_PD_llama_test.csv"
    ),
)


# ============================================================
# DONE
# ============================================================

print("\n\n")

print("=" * 75)

print(
    "ALL FOUR SFT EXPERIMENTS COMPLETED"
)

print("=" * 75)

print(
    "\nGenerated files:"
)

print(
    r"1. Set3_SFT_U_llama_test.csv"
)

print(
    r"2. Set3_SFT_U_C_llama_test.csv"
)

print(
    r"3. Set3_\SFT_U_C_R_llama_test.csv"
)

print(
    r"4. Set3_SFT_U_C_R_PD_llama_test.csv"
)

print("=" * 75)

D:\stdFurqan\FYP_AA\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

==============================================
DATASET
==============================================
Train shape : (17, 11)
Test shape  : (255, 11)

Columns:
['Language', 'Topic', 'User Role', 'Model Role', 'Power Distance', 'Register', 'Pragmatic Genre', 'Sensitivity', 'User Utterance', 'Context', 'Gold Response']

==============================================


================ GPU INFO ================
GPU : NVIDIA GeForce RTX 4080 SUPER
Total VRAM : 15.99 GB
Allocated : 0.00 GB
Reserved  : 0.00 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U
INPUT COLUMNS: ['User Utterance']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 0.00 GB
Reserved  : 0.00 GB
Max Allocated : 0.00 GB
Max Reserved  : 0.00 GB
==========================================


Loading FRESH Qwen model...

Loading weights: 100%|██████████| 291/291 [00:04<00:00, 64.41it/s]

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

================ MEMORY AFTER MODEL LOAD ================
Allocated : 7.43 GB
Reserved  : 9.51 GB
Max Allocated : 8.25 GB
Max Reserved  : 9.51 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 17/17 [00:00<00:00, 617.97it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 17
Maximum total tokens : 203
Maximum response tokens : 85
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 7.43 GB
Reserved  : 9.51 GB
Max Allocated : 8.25 GB
Max Reserved  : 9.51 GB
==========================================



================================================
TRAINING U
================================================

================================================
TRAINING COMPLETE
Training time: 1.22 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 7.48 GB
Reserved  : 9.80 GB
Max Allocated : 9.04 GB
Max Reserved  : 9.80 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s]

Before generate : 7.48 GB allocated | 9.80 GB reserved

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

After generate  : 7.48 GB allocated | 9.80 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 101
Maximum So Far : 101
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:   4%|▍         | 10/255 [00:19<08:02,  1.97s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 103
Maximum So Far : 115
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:   8%|▊         | 20/255 [00:41<09:15,  2.36s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 100
Maximum So Far : 115
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  12%|█▏        | 30/255 [01:02<07:40,  2.05s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 89
Maximum So Far : 122
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  16%|█▌        | 40/255 [01:21<07:27,  2.08s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 109
Maximum So Far : 122
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  20%|█▉        | 50/255 [01:43<08:07,  2.38s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 89
Maximum So Far : 122
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  24%|██▎       | 60/255 [02:03<07:32,  2.32s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 95
Maximum So Far : 122
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  27%|██▋       | 70/255 [02:27<07:49,  2.54s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 115
Maximum So Far : 122
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  31%|███▏      | 80/255 [02:52<07:14,  2.48s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 96
Maximum So Far : 122
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  35%|███▌      | 90/255 [03:14<06:02,  2.20s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 92
Maximum So Far : 122
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  39%|███▉      | 100/255 [03:33<05:15,  2.04s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 98
Maximum So Far : 122
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  43%|████▎     | 110/255 [03:53<04:46,  1.98s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 101
Maximum So Far : 124
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  47%|████▋     | 120/255 [04:12<03:57,  1.76s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 108
Maximum So Far : 124
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  51%|█████     | 130/255 [04:38<05:08,  2.47s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 111
Maximum So Far : 124
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  55%|█████▍    | 140/255 [05:00<03:59,  2.08s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 100
Maximum So Far : 124
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  59%|█████▉    | 150/255 [05:24<04:11,  2.40s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 111
Maximum So Far : 124
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  63%|██████▎   | 160/255 [05:46<03:20,  2.11s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 115
Maximum So Far : 124
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  67%|██████▋   | 170/255 [06:10<03:32,  2.49s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 106
Maximum So Far : 126
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  71%|███████   | 180/255 [06:33<03:00,  2.41s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 101
Maximum So Far : 126
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  75%|███████▍  | 190/255 [06:59<02:55,  2.70s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 101
Maximum So Far : 126
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  78%|███████▊  | 200/255 [07:26<02:30,  2.73s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 115
Maximum So Far : 135
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  82%|████████▏ | 210/255 [07:51<01:54,  2.55s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 92
Maximum So Far : 135
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  86%|████████▋ | 220/255 [08:14<01:24,  2.43s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 89
Maximum So Far : 135
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  90%|█████████ | 230/255 [08:34<00:59,  2.39s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 118
Maximum So Far : 135
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  94%|█████████▍| 240/255 [08:59<00:38,  2.55s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 111
Maximum So Far : 135
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation:  98%|█████████▊| 250/255 [09:24<00:12,  2.58s/it]

Before generate : 7.48 GB allocated | 9.62 GB reserved
After generate  : 7.48 GB allocated | 9.62 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 114
Maximum So Far : 135
Allocated VRAM : 7.48 GB
Reserved VRAM  : 9.62 GB
----------------------------------------

Generation: 100%|██████████| 255/255 [09:36<00:00,  2.26s/it]

Saved -> Set3_SFT_U_llama_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 1.97 GB
Reserved  : 7.17 GB
Max Allocated : 9.04 GB
Max Reserved  : 9.80 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C
INPUT COLUMNS: ['User Utterance', 'Context']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 1.97 GB
Reserved  : 7.17 GB
Max Allocated : 1.97 GB
Max Reserved  : 7.17 GB
==========================================


Loading FRESH Qwen model...

Loading weights: 100%|██████████| 291/291 [00:04<00:00, 65.13it/s]

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

================ MEMORY AFTER MODEL LOAD ================
Allocated : 9.40 GB
Reserved  : 11.48 GB
Max Allocated : 10.22 GB
Max Reserved  : 11.48 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 17/17 [00:00<00:00, 1307.43it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 17
Maximum total tokens : 326
Maximum response tokens : 85
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 9.40 GB
Reserved  : 11.48 GB
Max Allocated : 10.22 GB
Max Reserved  : 11.48 GB
==========================================



================================================
TRAINING U_C
================================================

================================================
TRAINING COMPLETE
Training time: 1.36 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 9.44 GB
Reserved  : 11.76 GB
Max Allocated : 11.21 GB
Max Reserved  : 11.76 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s]

Before generate : 9.44 GB allocated | 11.76 GB reserved
After generate  : 9.44 GB allocated | 11.76 GB reserved

Generation:   0%|          | 1/255 [00:02<09:26,  2.23s/it]

----------------------------------------
Sample         : 0
Prompt Tokens  : 155
Maximum So Far : 155
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:   4%|▍         | 10/255 [00:20<08:48,  2.16s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.61 GB reserved

Generation:   4%|▍         | 11/255 [00:22<09:27,  2.33s/it]

----------------------------------------
Sample         : 10
Prompt Tokens  : 159
Maximum So Far : 183
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:   8%|▊         | 20/255 [00:43<08:46,  2.24s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.61 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 175
Maximum So Far : 185
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  12%|█▏        | 30/255 [01:05<08:40,  2.31s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 154
Maximum So Far : 205
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  16%|█▌        | 40/255 [01:24<06:42,  1.87s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 157
Maximum So Far : 205
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  20%|█▉        | 50/255 [01:41<05:17,  1.55s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 140
Maximum So Far : 205
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  24%|██▎       | 60/255 [02:01<05:44,  1.77s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 135
Maximum So Far : 205
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  27%|██▋       | 70/255 [02:24<07:01,  2.28s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.63 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 176
Maximum So Far : 205
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  31%|███▏      | 80/255 [02:47<06:20,  2.17s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.63 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 186
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  35%|███▌      | 90/255 [03:10<06:18,  2.29s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 154
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  39%|███▉      | 100/255 [03:26<03:51,  1.50s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 161
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  43%|████▎     | 110/255 [03:48<04:34,  1.89s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 151
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  47%|████▋     | 120/255 [04:07<04:30,  2.00s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.60 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 152
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  51%|█████     | 130/255 [04:33<05:05,  2.45s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.63 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 177
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  55%|█████▍    | 140/255 [04:55<04:01,  2.10s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 140
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  59%|█████▉    | 150/255 [05:14<03:26,  1.97s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 152
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  63%|██████▎   | 160/255 [05:31<02:38,  1.67s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.60 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 176
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  67%|██████▋   | 170/255 [05:51<02:49,  1.99s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 141
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  71%|███████   | 180/255 [06:13<02:48,  2.25s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 146
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  75%|███████▍  | 190/255 [06:38<02:37,  2.42s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 139
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  78%|███████▊  | 200/255 [07:05<02:24,  2.63s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.63 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 171
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  82%|████████▏ | 210/255 [07:30<01:51,  2.47s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 136
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  86%|████████▋ | 220/255 [07:50<01:16,  2.18s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 129
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  90%|█████████ | 230/255 [08:09<00:47,  1.91s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.61 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 174
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  94%|█████████▍| 240/255 [08:34<00:37,  2.53s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.59 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 160
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation:  98%|█████████▊| 250/255 [08:56<00:11,  2.23s/it]

Before generate : 9.44 GB allocated | 11.59 GB reserved
After generate  : 9.44 GB allocated | 11.63 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 179
Maximum So Far : 225
Allocated VRAM : 9.44 GB
Reserved VRAM  : 11.59 GB
----------------------------------------

Generation: 100%|██████████| 255/255 [09:09<00:00,  2.15s/it]

Saved -> Set3_SFT_U_C_llama_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 3.93 GB
Reserved  : 9.12 GB
Max Allocated : 11.21 GB
Max Reserved  : 11.76 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C_R
INPUT COLUMNS: ['User Utterance', 'Context', 'User Role', 'Model Role']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 3.93 GB
Reserved  : 9.12 GB
Max Allocated : 3.93 GB
Max Reserved  : 9.12 GB
==========================================


Loading FRESH Qwen model...

Loading weights: 100%|██████████| 291/291 [00:04<00:00, 65.12it/s]

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

================ MEMORY AFTER MODEL LOAD ================
Allocated : 11.36 GB
Reserved  : 13.43 GB
Max Allocated : 12.18 GB
Max Reserved  : 13.43 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 17/17 [00:00<00:00, 1297.41it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 17
Maximum total tokens : 341
Maximum response tokens : 85
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 11.36 GB
Reserved  : 13.43 GB
Max Allocated : 12.18 GB
Max Reserved  : 13.43 GB
==========================================



================================================
TRAINING U_C_R
================================================

================================================
TRAINING COMPLETE
Training time: 1.40 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 11.40 GB
Reserved  : 13.71 GB
Max Allocated : 13.19 GB
Max Reserved  : 13.71 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context', 'User Role', 'Model Role']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s]

Before generate : 11.40 GB allocated | 13.71 GB reserved
After generate  : 11.40 GB allocated | 13.71 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 172
Maximum So Far : 172
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:   4%|▍         | 10/255 [00:23<10:42,  2.62s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 176
Maximum So Far : 201
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:   8%|▊         | 20/255 [00:46<08:13,  2.10s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 189
Maximum So Far : 202
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  12%|█▏        | 30/255 [01:11<09:17,  2.48s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 170
Maximum So Far : 223
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  16%|█▌        | 40/255 [01:33<08:23,  2.34s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 175
Maximum So Far : 223
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  20%|█▉        | 50/255 [01:56<08:00,  2.34s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 155
Maximum So Far : 223
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  24%|██▎       | 60/255 [02:16<06:53,  2.12s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 153
Maximum So Far : 223
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  27%|██▋       | 70/255 [02:39<07:15,  2.35s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 192
Maximum So Far : 223
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  31%|███▏      | 80/255 [03:01<06:15,  2.15s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.59 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 207
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  35%|███▌      | 90/255 [03:24<06:23,  2.33s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 169
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  39%|███▉      | 100/255 [03:40<04:01,  1.56s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 184
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  43%|████▎     | 110/255 [03:56<03:24,  1.41s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 165
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  47%|████▋     | 120/255 [04:14<03:54,  1.74s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.56 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 169
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  51%|█████     | 130/255 [04:37<04:51,  2.33s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 192
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  55%|█████▍    | 140/255 [04:58<03:57,  2.06s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 155
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  59%|█████▉    | 150/255 [05:16<03:11,  1.82s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 167
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  63%|██████▎   | 160/255 [05:37<03:01,  1.91s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 190
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  67%|██████▋   | 170/255 [05:58<02:51,  2.01s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 155
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  71%|███████   | 180/255 [06:17<02:22,  1.90s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 161
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  75%|███████▍  | 190/255 [06:40<02:28,  2.28s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 154
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  78%|███████▊  | 200/255 [07:04<02:09,  2.36s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 189
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  82%|████████▏ | 210/255 [07:27<01:39,  2.21s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 210
Prompt Tokens  : 151
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  86%|████████▋ | 220/255 [07:43<01:00,  1.74s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.55 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 145
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  90%|█████████ | 230/255 [08:02<00:46,  1.84s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 189
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  94%|█████████▍| 240/255 [08:22<00:32,  2.15s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 174
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation:  98%|█████████▊| 250/255 [08:44<00:11,  2.26s/it]

Before generate : 11.40 GB allocated | 13.55 GB reserved
After generate  : 11.40 GB allocated | 13.58 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 194
Maximum So Far : 243
Allocated VRAM : 11.40 GB
Reserved VRAM  : 13.55 GB
----------------------------------------

Generation: 100%|██████████| 255/255 [08:56<00:00,  2.11s/it]

Saved -> Set3_SFT_U_C_R_llama_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 5.89 GB
Reserved  : 11.08 GB
Max Allocated : 13.19 GB
Max Reserved  : 13.71 GB
==========================================




===========================================================================
STARTING SFT EXPERIMENT: U_C_R_PD
INPUT COLUMNS: ['User Utterance', 'Context', 'User Role', 'Model Role', 'Power Distance']
EPOCHS: 10
===========================================================================

================ MEMORY BEFORE MODEL LOAD ================
Allocated : 5.89 GB
Reserved  : 11.08 GB
Max Allocated : 5.89 GB
Max Reserved  : 11.08 GB
==========================================


Loading FRESH Qwen model...

Loading weights: 100%|██████████| 291/291 [00:04<00:00, 67.01it/s]

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

================ MEMORY AFTER MODEL LOAD ================
Allocated : 13.32 GB
Reserved  : 15.39 GB
Max Allocated : 14.14 GB
Max Reserved  : 15.39 GB
==========================================


Building training examples...

Preparing SFT data: 100%|██████████| 17/17 [00:00<00:00, 1259.19it/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training examples : 17
Maximum total tokens : 347
Maximum response tokens : 85
MAX_LENGTH : 2048

================ MEMORY BEFORE TRAINING ================
Allocated : 13.32 GB
Reserved  : 15.39 GB
Max Allocated : 14.14 GB
Max Reserved  : 15.39 GB
==========================================



================================================
TRAINING U_C_R_PD
================================================

================================================
TRAINING COMPLETE
Training time: 2.87 minutes
================================================

================ MEMORY AFTER TRAINING ================
Allocated : 13.35 GB
Reserved  : 15.67 GB
Max Allocated : 15.16 GB
Max Reserved  : 15.67 GB
==========================================


================================================
GENERATING TEST RESPONSES
Input columns: ['User Utterance', 'Context', 'User Role', 'Model Role', 'Power Distance']
Test samples: 255
================================================

Generation:   0%|          | 0/255 [00:00<?, ?it/s]

Before generate : 13.35 GB allocated | 15.67 GB reserved
After generate  : 13.35 GB allocated | 15.67 GB reserved

----------------------------------------
Sample         : 0
Prompt Tokens  : 178
Maximum So Far : 178
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:   4%|▍         | 10/255 [00:33<15:15,  3.74s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 10
Prompt Tokens  : 182
Maximum So Far : 207
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:   8%|▊         | 20/255 [01:03<11:36,  2.96s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 20
Prompt Tokens  : 195
Maximum So Far : 208
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  12%|█▏        | 30/255 [01:35<12:41,  3.38s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 30
Prompt Tokens  : 176
Maximum So Far : 229
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  16%|█▌        | 40/255 [02:03<08:09,  2.28s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 40
Prompt Tokens  : 181
Maximum So Far : 229
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  20%|█▉        | 50/255 [02:33<10:24,  3.04s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 50
Prompt Tokens  : 161
Maximum So Far : 229
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  24%|██▎       | 60/255 [02:59<09:06,  2.80s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 60
Prompt Tokens  : 159
Maximum So Far : 229
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  27%|██▋       | 70/255 [03:29<09:45,  3.16s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.59 GB reserved

----------------------------------------
Sample         : 70
Prompt Tokens  : 198
Maximum So Far : 229
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  31%|███▏      | 80/255 [04:05<10:32,  3.61s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.59 GB reserved

----------------------------------------
Sample         : 80
Prompt Tokens  : 213
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  35%|███▌      | 90/255 [04:40<09:16,  3.37s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 90
Prompt Tokens  : 175
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  39%|███▉      | 100/255 [05:04<05:58,  2.31s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 100
Prompt Tokens  : 190
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  43%|████▎     | 110/255 [05:32<06:13,  2.58s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 110
Prompt Tokens  : 171
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  47%|████▋     | 120/255 [05:58<05:59,  2.66s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 120
Prompt Tokens  : 175
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  51%|█████     | 130/255 [06:32<07:11,  3.45s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.59 GB reserved

----------------------------------------
Sample         : 130
Prompt Tokens  : 198
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  55%|█████▍    | 140/255 [07:05<05:53,  3.08s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 140
Prompt Tokens  : 161
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  59%|█████▉    | 150/255 [07:34<04:36,  2.63s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved

Generation:  59%|█████▉    | 151/255 [07:37<05:00,  2.89s/it]

After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 150
Prompt Tokens  : 173
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  63%|██████▎   | 160/255 [08:06<04:15,  2.69s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 160
Prompt Tokens  : 196
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  67%|██████▋   | 170/255 [08:33<03:30,  2.48s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 170
Prompt Tokens  : 161
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  71%|███████   | 180/255 [08:58<03:46,  3.02s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 180
Prompt Tokens  : 167
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  75%|███████▍  | 190/255 [09:32<03:40,  3.40s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 190
Prompt Tokens  : 160
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  78%|███████▊  | 200/255 [10:05<02:46,  3.03s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.59 GB reserved

----------------------------------------
Sample         : 200
Prompt Tokens  : 195
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  82%|████████▏ | 210/255 [10:38<02:32,  3.40s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

Generation:  83%|████████▎ | 211/255 [10:41<02:11,  2.99s/it]

----------------------------------------
Sample         : 210
Prompt Tokens  : 157
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  86%|████████▋ | 220/255 [11:02<01:27,  2.51s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 220
Prompt Tokens  : 151
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  90%|█████████ | 230/255 [11:29<01:16,  3.07s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 230
Prompt Tokens  : 195
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  94%|█████████▍| 240/255 [12:00<00:47,  3.14s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.58 GB reserved

----------------------------------------
Sample         : 240
Prompt Tokens  : 180
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation:  98%|█████████▊| 250/255 [12:33<00:15,  3.01s/it]

Before generate : 13.35 GB allocated | 15.58 GB reserved
After generate  : 13.35 GB allocated | 15.59 GB reserved

----------------------------------------
Sample         : 250
Prompt Tokens  : 200
Maximum So Far : 249
Allocated VRAM : 13.35 GB
Reserved VRAM  : 15.58 GB
----------------------------------------

Generation: 100%|██████████| 255/255 [12:51<00:00,  3.03s/it]

Saved -> Set3_SFT_U_C_R_PD_llama_test.csv

Cleaning up model...

================ FINAL MEMORY AFTER CLEANUP ================
Allocated : 7.84 GB
Reserved  : 13.04 GB
Max Allocated : 15.16 GB
Max Reserved  : 15.67 GB
==========================================




===========================================================================
ALL FOUR SFT EXPERIMENTS COMPLETED
===========================================================================

Generated files:
1. Set3_SFT_U_llama_test.csv
2. Set3_SFT_U_C_llama_test.csv
3. Set3_\SFT_U_C_R_llama_test.csv
4. Set3_SFT_U_C_R_PD_llama_test.csv
===========================================================================